== *Artificer*
:toc:

[width="99%",cols="11%,6%,39%,9%,7%,8%,4%,4%,4%,4%,4%",options="header",]
|===
| | | | | | |*_Spell Slots per Spell Level_* | | | |
|*_Level_* a|
*_Prof._*

*_Bonus_*

|*_Features_* |*_Infusions Known_* |*_Infused Items_* |*_Cantrips
Known_* |*_1st_* |*_2nd_* |*_3rd_* |*_4th_* |*_5th_*

|*1st* |*+2* |*Optional Rule: Firearm Proficiency, Magical Tinkering,
Spellcasting* |*—* |*—* |*2* |*2* |*—* |*—* |*—* |*—*

|*2nd* |*+2* |*Infuse Item* |*4* |*2* |*2* |*2* |*—* |*—* |*—* |*—*

|*3rd* |*+2* |
*Artificer Specialist,*

*The Right Tool for the Job*

|*4* |*2* |*2* |*3* |*—* |*—* |*—* |*—*

|*4th* |*+2* |*Ability Score Improvement* |*4* |*2* |*2* |*3* |*—* |*—*
|*—* |*—*

|*5th* |*+3* |*Artificer Specialist Feature* |*4* |*2* |*2* |*4* |*2*
|*—* |*—* |*—*

|*6th* |*+3* |*Tool Expertise* |*6* |*3* |*2* |*4* |*2* |*—* |*—* |*—*

|*7th* |*+3* |*Flash of Genius* |*6* |*3* |*2* |*4* |*3* |*—* |*—* |*—*

|*8th* |*+3* |*Ability Score Improvement* |*6* |*3* |*2* |*4* |*3* |*—*
|*—* |*—*

|*9th* |*+4* |*Artificer Specialist Feature* |*6* |*3* |*2* |*4* |*3*
|*2* |*—* |*—*

|*10th* |*+4* |*Magic Item Adept* |*8* |*4* |*3* |*4* |*3* |*2* |*—*
|*—*

|*11th* |*+4* |*Spell-Storing Item* |*8* |*4* |*3* |*4* |*3* |*3* |*—*
|*—*

|*12th* |*+4* |*Ability Score Improvement* |*8* |*4* |*3* |*4* |*3* |*3*
|*—* |*—*

|*13th* |*+5* |*—* |*8* |*4* |*3* |*4* |*3* |*3* |*1* |*—*

|*14th* |*+5* |*Magic Item Savant* |*10* |*5* |*4* |*4* |*3* |*3* |*1*
|*—*

|*15th* |*+5* |*Artificer Specialist Feature* |*10* |*5* |*4* |*4* |*3*
|*3* |*2* |*—*

|*16th* |*+5* |*Ability Score Improvement* |*10* |*5* |*4* |*4* |*3*
|*3* |*2* |*—*

|*17th* |*+6* |*—* |*10* |*5* |*4* |*4* |*3* |*3* |*3* |*1*

|*18th* |*+6* |*Magic Item Master* |*12* |*6* |*4* |*4* |*3* |*3* |*3*
|*1*

|*19th* |*+6* |*Ability Score Improvement* |*12* |*6* |*4* |*4* |*3*
|*3* |*3* |*2*

|*20th* |*+6* |*Soul of Artifice* |*12* |*6* |*4* |*4* |*3* |*3* |*3*
|*2*
|===

=== *Spells Added to the Artificer Spell List*

[width="99%"]
|===
|
*Arcane Weapon* +
_Cantrip transmutation_

*Casting Time:* 1 action

*Range:* 120 ft

*Components:* V, S

*Duration:* Instantaneous
|
You channel arcane energy into one Artificer Spellcasting Focus you're
holding, and choose one damage type: acid, cold, fire, lightning,
poison, or thunder. You make a ranged spell attack against a creature in
the range, dealing 1d8 damage of the chosen type to any target you hit.

This spell's damage increases by 1d8 when you reach 5th level (2d8),
11th level (3d8), and 17th level (4d8).

|===

[width="99%"]
|===
|
*Hit Points*

*_Hit Dice_*: 1d8

*_Hit Points at 1st Level_*: 8 + your Constitution modifier

*_Hit Points at Higher Levels_*: 1d8 (or 5) + your Constitution modifier
per Artificer level after 1st
|
*Proficiencies*

*_Armor_*: light armor, medium armor, shields

*_Weapons_*: simple weapons, firearms

*_Tools_*: thieves' tools, tinker's tools, one type of artisan's tools
of your choice

*_Saving Throws_*: Constitution, Intelligence

*_Skills_*: Choose 2 from Arcana, History, Investigation, Medicine,
Nature, Perception, and Sleight of Hand.
a|
*Starting Equipment*

You start with the following items, plus anything provided by your
background.

* {blank}
+
____
{empty}any two simple weapons of your choice.
____
* {blank}
+
____
{empty}a light crossbow and 20 bolts.
____
* {blank}
+
____
{empty}(a) studded leather armor or (b) scale mail.
____
* {blank}
+
____
{empty}thieves' tools and a dungeoneer's pack.
____
|===

=== *Optional Rule: Firearm Proficiency*

The secrets of creating and operating gunpowder weapons have been
discovered in various corners of the D&D multiverse. If your Dungeon
Master uses the rules on firearms in chapter 9 of the Dungeon Master's
Guide and your artificer has been exposed to the operation of such
weapons, your artificer is proficient with them.

=== *Magical Tinkering*

At 1st level, you learn how to invest a spark of magic into mundane
objects. To use this ability, you must have thieves' tools or artisan's
tools in hand. You then touch a Tiny non magical object as an action and
give it one of the following magical properties of your choice:

* {blank}
+
____
The object sheds bright light in a 5-foot radius and dim light for an
additional 5 feet.
____
* {blank}
+
____
Whenever tapped by a creature, the object emits a recorded message that
can be heard up to 10 feet away. You utter the message when you bestow
this property on the object, and the recording can be no more than 6
seconds long.
____
* {blank}
+
____
The object continuously emits your choice of an odor or a nonverbal
sound (wind, waves, chirping, or the like). The chosen phenomenon is
perceivable up to 10 feet away.
____
* {blank}
+
____
A static visual effect appears on one of the object's surfaces. This
effect can be a picture, up to 25 words of text, lines and shapes, or a
mixture of these elements, as you like.
____

The chosen property lasts indefinitely. As an action, you can touch the
object and end the property early.

You can bestow magic on multiple objects, touching one object each time
you use this feature, though a single object can only bear one property
at a time. The maximum number of objects you can affect with this
feature at one time is equal to your Intelligence modifier (minimum of
one object). If you try to exceed your maximum, the oldest property
immediately ends, and then the new property applies.

=== *Spellcasting*

==== *Cantrips*

You can prepare two Cantrips, you learn one extra at 10th level and
another at 14th level. Those Cantrips are from the Artificer Spell List.
Additionally you always have the _Arcane Weapon_ cantrip, and doesn’t
count for the amount of cantrips that you know.

==== *Spell Slots*

Your Class table shows how many spell slots you have to cast your spells
of 1st level and higher. To cast one of these spells, you must expend a
slot of the spell's level or higher. You regain all expended spell slots
when you finish a long rest.

==== *Preparing and Casting Spells*

Whenever you finish a Long Rest, you can replace any Spell you have
prepared for this Class with another Spell from your Class Spell List.
At higher levels in this Class, you can prepare more Spells. The amount
of spells you can prepare is equal to your Intelligence modifier + half
your Artificer level, rounded down (minimum of 1). Additionally, the
amount of spells for each level is equal to the amount of Spell Slots
that you have for your current level. Additionally, you always have the
*_Detect Magic_* spell and don't count on your spell prepared for this
class and you can cast it as a ritual as an action.

==== *Spellcasting Ability*

Your Spellcasting Ability is Intelligence.

____
*_Spell save DC_* = 8 + your proficiency bonus + your Intelligence
modifier

*_Spell attack modifier_* = your proficiency bonus + your Intelligence
modifier
____

==== *Spellcasting Focus*

Your Spellcasting Focus is any Tools that you have proficiency with.
Additionally, through your Infusions you will be able to use them as
Spellcasting Focus if the Infusion specifies it.

=== *Infuse Item*

At 2nd level, you gain the ability to imbue mundane items with certain
magical infusions. The magic items you create with this feature are
effectively prototypes of permanent items.

==== *Infusions Known*

When you gain this feature, pick four artificer infusions to learn,
choosing from the "Artificer Infusions" section at the end of the
class's description. You learn additional infusions of your choice when
you reach certain levels in this class, as shown in the Infusions Known
column of the Artificer table.

Whenever you gain a level in this class, you can replace one of the
artificer infusions you learned with a new one.

==== *Artificer Infusions*

Artificers have invented numerous magical infusions, extraordinary
processes that rapidly create magic items. To many, artificers seem like
wonderworkers, accomplishing in hours what others need weeks to
complete.

The description of each of the following infusions details the type of
item that can receive it, along with whether the resulting magic item
requires attunement.

Some infusions specify a minimum artificer level. You can't learn such
an infusion until you are at least that level.

Unless an infusion's description says otherwise, you can't learn an
infusion more than once.

==== *Infusing an Item*

Whenever you finish a long rest, you can touch a nonmagical object and
imbue it with one of your artificer infusions, turning it into a magic
item. An infusion works on only certain kinds of objects, as specified
in the infusion's description. If the item requires attunement, you can
attune yourself to it the instant you infuse the item. If you decide to
attune to the item later, you must do so using the normal process for
attunement (see "Attunement" in chapter 7 of the Dungeon Master's
Guide).

Your infusion remains in an item indefinitely, but when you die, the
infusion vanishes after a number of days have passed equal to your
Intelligence modifier (minimum of 1 day). The infusion also vanishes if
you give up your knowledge of the infusion for another one.

You can infuse more than one non magical object at the end of a long
rest; the maximum number of objects appears in the Infused Items column
of the Artificer table. You must touch each of the objects, and each of
your infusions can be in only one object at a time. Moreover, no object
can bear more than one of your infusions at a time. If you try to exceed
your maximum number of infusions, the oldest infusion immediately ends,
and then the new infusion applies.

If an infusion ends on an item that contains other things, like a bag of
holding, its contents harmlessly appear in and around its space.

=== *Artificer Specialist*

At 3rd level, you choose the type of specialist you are, each of which
is detailed at the end of the class's description. Your choice grants
you features at 5th level and again at 9th and 15th level.

=== *The Right Tool for the Job*

At 3rd level, you learn how to produce exactly the tool you need: with
thieves' tools or artisan's tools in hand, you can magically create one
set of artisan's tools in an unoccupied space within 5 feet of you. This
creation requires 1 hour of uninterrupted work, which can coincide with
a short or long rest. Though the product of magic, the tools are
nonmagical, and they vanish when you use this feature again.

=== *Ability Score Improvement*

When you reach 4th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Artificer Specialist Feature*

At 5th level, you gain a feature granted by your Artificer Specialist
choice.

=== *Tool Expertise*

Starting at 6th level, your proficiency bonus is doubled for any ability
check you make that uses your proficiency with a tool.

=== *Flash of Genius*

Starting at 7th level, you gain the ability to come up with solutions
under pressure. When you or another creature you can see within 30 feet
of you makes an ability check or a saving throw, you can use your
reaction to add your Intelligence modifier to the roll.

You can use this feature a number of times equal to your Intelligence
modifier (minimum of once). You regain all expended uses when you finish
a long rest.

=== *Ability Score Improvement*

When you reach 8th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Artificer Specialist Feature*

At 9th level, you gain a feature granted by your Artificer Specialist
choice.

=== *Magic Item Adept*

When you reach 10th level, you achieve a profound understanding of how
to use and make magic items:

You can attune to up to four magic items at once.

If you craft a magic item with a rarity of common or uncommon, it takes
you a quarter of the normal time, and it costs you half as much of the
usual gold.

=== *Spell-Storing Item*

At 11th level, you learn how to store a spell in an object. Whenever you
finish a long rest, you can touch one simple or martial weapon or one
item that you can use as a spellcasting focus, and you store a spell in
it, choosing a 1st- or 2nd-level spell from the artificer spell list
that requires 1 action to cast (you needn't have it prepared).

While holding the object, a creature can take an action to produce the
spell's effect from it, using your spellcasting ability modifier. If the
spell requires concentration, the creature must concentrate. The spell
stays in the object until it's been used a number of times equal to
twice your Intelligence modifier (minimum of twice) or until you use
this feature again to store a spell in an object.

=== *Ability Score Improvement*

When you reach 12th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Magic Item Savant*

At 14th level, your skill with magic items deepens more:

You can attune to up to five magic items at once.

You ignore all class, race, spell, and level requirements on attuning to
or using a magic item.

=== *Artificer Specialist Feature*

At 15th level, you gain a feature granted by your Artificer Specialist
choice.

=== *Ability Score Improvement*

When you reach 16th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Magic Item Master*

Starting at 18th level, you can attune to up to six magic items at once.

=== *Ability Score Improvement*

When you reach 19th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Soul of Artifice*

At 20th level, you develop a mystical connection to your magic items,
which you can draw on for protection:

You gain a +1 bonus to all saving throws per magic item you are
currently attuned to.

If you're reduced to 0 hit points but not killed outright, you can use
your reaction to end one of your artificer infusions, causing you to
drop to 1 hit point instead of 0.

include::artificer_subclass.adoc[]

