== *Artificer Specialists*
:toclevels: 2

=== *Alchemist*

An Alchemist is an expert at combining reagents to produce mystical
effects. Alchemists use their creations to give life and to leech it
away. Alchemy is the oldest of artificer traditions, and its versatility
has long been valued during times of war and peace.

==== *3rd LEVEL: Tool Proficiency*

When you adopt this specialization at 3rd level, you gain proficiency
with alchemist's supplies. If you already have this proficiency, you
gain proficiency with one other type of artisan's tools of your choice.

==== *3rd LEVEL: Alchemist Spells*

Starting at 3rd level, you always have certain spells prepared after you
reach particular levels in this class, as shown in the Alchemist Spells
table. These spells count as artificer spells for you, but they don't
count against the number of artificer spells you prepare.

==== *Alchemist Spells*

[width="100%",cols="32%,68%",options="header",]
|===
|*Artificer Level* |*Spell*
|3rd |healing word, ray of sickness
|5th |flaming sphere, Melf's acid arrow
|9th |gaseous form, mass healing word
|13th |blight, death ward
|17th |cloudkill, raise dead
|===

==== *3rd LEVEL: Experimental Elixir*

Beginning at 3rd level, whenever you finish a long rest, you can
magically produce an experimental elixir in an empty flask you touch.
Roll on the Experimental Elixir table for the elixir's effect, which is
triggered when someone drinks the elixir. As an action, a creature can
drink the elixir or administer it to an incapacitated creature.

Creating an experimental elixir requires you to have alchemist's
supplies on your person, and any elixir you create with this feature
lasts until it is drunk or until the end of your next long rest.

When you reach certain levels in this class, you can make more elixirs
at the end of a long rest: two at 6th level and three at 15th level.
Roll for each elixir's effect separately. Each elixir requires its own
flask.

You can create additional experimental elixirs by expending a spell slot
of 1st level or higher for each one. When you do so, you use your action
to create the elixir in an empty flask you touch, and you choose the
elixir's effect from the Experimental Elixir table.

===== *Experimental Elixir*

[width="100%",cols="6%,94%",options="header",]
|===
|*d6* |*Effect*
|1 |*Healing*. The drinker regains a number of hit points equal to 2d4 +
your Intelligence modifier.

|2 |*Swiftness*. The drinker's walking speed increases by 10 feet for 1
hour.

|3 |*Resilience*. The drinker gains a +1 bonus to AC for 10 minutes.

|4 |*Boldness*. The drinker can roll a d4 and add the number rolled to
every attack roll and saving throw they make for the next minute.

|5 |*Flight*. The drinker gains a flying speed of 10 feet for 10
minutes.

|6 |*Transformation*. The drinker's body is transformed as if by the
alter self spell. The drinker determines the transformation caused by
the spell, the effects of which last for 10 minutes.
|===

==== *5th LEVEL: Alchemical Savant*

At 5th level, you develop masterful command of magical chemicals,
enhancing the healing and damage you create through them. Whenever you
cast a spell using your alchemist's supplies as the spellcasting focus,
you gain a bonus to one roll of the spell. That roll must restore hit
points or be a damage roll that deals acid, fire, necrotic, or poison
damage, and the bonus equals your Intelligence modifier (minimum of +1).

==== *9th LEVEL: Restorative Reagents*

Starting at 9th level, you can incorporate restorative reagents into
some of your works:

* {blank}
+
____
Whenever a creature drinks an experimental elixir you created, the
creature gains temporary hit points equal to 2d6 + your Intelligence
modifier (minimum of 1 temporary hit point).
____
* {blank}
+
____
You can cast lesser restoration without expending a spell slot and
without preparing the spell, provided you use alchemist's supplies as
the spellcasting focus. You can do so a number of times equal to your
Intelligence modifier (minimum of once), and you regain all expended
uses when you finish a long rest.
____

==== *15th LEVEL: Chemical Mastery*

By 15th level, you have been exposed to so many chemicals that they pose
little risk to you, and you can use them to quickly end certain
ailments:

* {blank}
+
____
You gain resistance to acid damage and poison damage, and you are immune
to the poisoned condition.
____
* {blank}
+
____
You can cast greater restoration and heal without expending a spell
slot, without preparing the spell, and without material components,
provided you use alchemist's supplies as the spellcasting focus. Once
you cast either spell with this feature, you can't cast that spell with
it again until you finish a long rest.
____

=== *Artillerist*

An Artillerist specializes in using magic to hurl energy, projectiles,
and explosions on a battlefield. This destructive power was valued by
all the armies of the Last War. Now that the war is over, some members
of this specialization have sought to build a more peaceful world by
using their powers to fight the resurgence of strife in Khorvaire.

==== *3rd LEVEL: Tool Proficiency*

When you adopt this specialization at 3rd level, you gain proficiency
with woodcarver's tools. If you already have this proficiency, you gain
proficiency with one other type of artisan's tools of your choice.

==== *3rd LEVEL: Artillerist Spells*

Starting at 3rd level, you always have certain spells prepared after you
reach particular levels in this class, as shown in the Artillerist
Spells table. These spells count as artificer spells for you, but they
don't count against the number of artificer spells you prepare.

===== *Artillerist Spells*

[width="100%",cols="35%,65%",options="header",]
|===
|*Artificer Level* |*Spell*
|3rd |shield, thunderwave
|5th |scorching ray, shatter
|9th |fireball, wind wall
|13th |ice storm, wall of fire
|17th |cone of cold, wall of force
|===

==== *3rd LEVEL: Eldritch Cannon*

At 3rd level, you learn how to create a magical cannon. Using
woodcarver's tools or smith's tools, you can take an action to magically
create a Small or Tiny eldritch cannon in an unoccupied space on a
horizontal surface within 5 feet of you. A Small eldritch cannon
occupies its space, and a Tiny one can be held in one hand.

Once you create a cannon, you can't do so again until you finish a long
rest or until you expend a spell slot of 1st level or higher. You can
have only one cannon at a time and can't create one while your cannon is
present.

The cannon is a magical object. Regardless of size, the cannon has an AC
of 18 and a number of hit points equal to five times your artificer
level. It is immune to poison damage and psychic damage, and all
conditions. If it is forced to make an ability check or a saving throw,
treat all its ability scores as 10 (+0). If the mending spell is cast on
it, it regains 2d6 hit points. It disappears if it is reduced to 0 hit
points or after 1 hour. You can dismiss it early as an action.

When you create the cannon, you determine its appearance and whether it
has legs. You also decide which type it is, choosing from the options on
the Eldritch Cannons table. On each of your turns, you can take a bonus
action to cause the cannon to activate if you are within 60 feet of it.
As part of the same bonus action, you can direct the cannon to walk or
climb up to 15 feet to an unoccupied space, provided it has legs.

===== *Eldritch Cannons*

[width="100%",cols="15%,85%",options="header",]
|===
|*Cannon* |*Activation*
|Flamethrower |The cannon exhales fire in an adjacent 15-foot cone that
you designate. Each creature in that area must make a Dexterity saving
throw against your spell save DC, taking 2d8 fire damage on a failed
save or half as much damage on a successful one. The fire ignites any
flammable objects in the area that aren't being worn or carried.

a|
Force

Ballista

|Make a ranged spell attack, originating from the cannon, at one
creature or object within 120 feet of it. On a hit, the target takes 2d8
force damage, and if the target is a creature, it is pushed up to 5 feet
away from the cannon.

|Protector |The cannon emits a burst of positive energy that grants
itself and each creature of your choice within 10 feet of it a number of
temporary hit points equal to 1d8 + your Intelligence modifier (minimum
of +1).
|===

==== *5th LEVEL: Arcane Firearm*

At 5th level, you know how to turn a wand, staff, or rod into an arcane
firearm, a conduit for your destructive spells. When you finish a long
rest, you can use woodcarver's tools to carve special sigils into a
wand, staff, or rod and thereby turn it into your arcane firearm. The
sigils disappear from the object if you later carve them on a different
item. The sigils otherwise last indefinitely.

You can use your arcane firearm as a spellcasting focus for your
artificer spells. When you cast an artificer spell through the firearm,
roll a d8, and you gain a bonus to one of the spell's damage rolls equal
to the number rolled.

==== *9th LEVEL: Explosive Cannon*

Starting at 9th level, every eldritch cannon you create is more
destructive:

* {blank}
+
____
The cannon's damage rolls all increase by 1d8.
____
* {blank}
+
____
As an action, you can command the cannon to detonate if you are within
60 feet of it. Doing so destroys the cannon and forces each creature
within 20 feet of it to make a Dexterity saving throw against your spell
save DC, taking 3d8 force damage on a failed save or half as much damage
on a successful one.
____
* {blank}

==== *15th LEVEL: Fortified Position*

Starting at 15th level, you're a master at forming well-defended
emplacements using Eldritch Cannon:

* {blank}
+
____
You and your allies have half cover while within 10 feet of a cannon you
create with Eldritch Cannon, as a result of a shimmering field of
magical protection that the cannon emits.
____
* {blank}
+
____
You can now have two cannons at the same time. You can create two with
the same action (but not the same spell slot), and you can activate both
of them with the same bonus action. You determine whether the cannons
are identical to each other or different. You can't create a third
cannon while you have two.
____

=== *Battle Smith*

Armies require protection, and someone has to put things back together
if defenses fail. A combination of protector and medic, a Battle Smith
is an expert at defending others and repairing both material and
personnel. To aid in their work, Battle Smiths are usually accompanied
by a steel defender, a protective companion of their own creation. Many
soldiers tell stories of nearly dying before being saved by a Battle
Smith and a steel defender.

Battle Smiths played a key role in House Cannith's work on battle
constructs and the original warforged, and after the Last War, these
artificers led efforts to aid those who were injured in the war's
horrific battles.

==== *3rd LEVEL: Tool Proficiency*

When you adopt this specialization at 3rd level, you gain proficiency
with smith's tools. If you already have this proficiency, you gain
proficiency with one other type of artisan's tools of your choice.

==== *3rd LEVEL: Battle Smith Spells*

Starting at 3rd level, you always have certain spells prepared after you
reach particular levels in this class, as shown in the Battle Smith
Spells table. These spells count as artificer spells for you, but they
don't count against the number of artificer spells you prepare.

===== *Battle Smith Spells*

[width="100%",cols="33%,67%",options="header",]
|===
|*Artificer Level* |*Spell*
|3rd |heroism, shield
|5th |branding smite, warding bond
|9th |aura of vitality, conjure barrage
|13th |aura of purity, fire shield
|17th |banishing smite, mass cure wounds
|===

==== *3rd LEVEL: Battle Ready*

When you reach 3rd level, your combat training and your experiments with
magic have paid off in two ways:

* {blank}
+
____
You gain proficiency with martial weapons.
____
* {blank}
+
____
When you attack with a magic weapon, you can use your Intelligence
modifier, instead of Strength or Dexterity modifier, for the attack and
damage rolls.
____

==== *3rd LEVEL: Steel Defender*

By 3rd level, your tinkering has borne you a faithful companion, a steel
defender. It is friendly to you and your companions, and it obeys your
commands. See this creature's game statistics in the steel defender stat
block, which uses your proficiency bonus (PB) in several places. You
determine the creature's appearance and whether it has two legs or four;
your choice has no effect on its game statistics.

In combat, the defender shares your initiative count, but it takes its
turn immediately after yours. It can move and use its reaction on its
own, but the only action it takes on its turn is the Dodge action,
unless you take a bonus action on your turn to command it to take
another action. That action can be one in its stat block or some other
action. If you are incapacitated, the defender can take any action of
its choice, not just Dodge.

If the mending spell is cast on it, it regains 2d6 hit points. If it has
died within the last hour, you can use your smith's tools as an action
to revive it, provided you are within 5 feet of it and you expend a
spell slot of 1st level or higher. The steel defender returns to life
after 1 minute with all its hit points restored.

At the end of a long rest, you can create a new steel defender if you
have your smith's tools with you. If you already have a steel defender
from this feature, the first one immediately perishes. The defender also
perishes if you die.

==== *5th LEVEL: Extra Attack*

Starting at 5th level, you can attack twice, rather than once, whenever
you take the Attack action on your turn.

==== *9th LEVEL: Arcane Jolt*

At 9th level, you learn new ways to channel arcane energy to harm or
heal. When either you hit a target with a magic weapon attack or your
steel defender hits a target, you can channel magical energy through the
strike to create one of the following effects:

* {blank}
+
____
The target takes an extra 2d6 force damage.
____
* {blank}
+
____
Choose one creature or object you can see within 30 feet of the target.
Healing energy flows into the chosen recipient, restoring 2d6 hit points
to it.
____

You can use this energy a number of times equal to your Intelligence
modifier (minimum of once), but you can do so no more than once on a
turn. You regain all expended uses when you finish a long rest.

==== *15th LEVEL: Improved Defender*

At 15th level, your Arcane Jolt and steel defender become more powerful:

* {blank}
+
____
The extra damage and the healing of your Arcane Jolt both increase to
4d6.
____
* {blank}
+
____
Your steel defender gains a +2 bonus to Armor Class.
____
* {blank}
+
____
Whenever your steel defender uses its Deflect Attack, the attacker takes
force damage equal to 1d4 + your Intelligence modifier.
____

