== *Barbarian*

[width="99%",cols="8%,6%,65%,9%,12%",options="header",]
|===
|*_Level_* |*_Prof. Bonus_* |*_Features_* |*_Rages_* |*_Rage Damage_*
|*1st* |*+2* |*Rage, Unarmored Defense* |*2* |*+2*
|*2nd* |*+2* |*Danger Sense, Reckless Attack* |*2* |*+2*
|*3rd* |*+2* |*Primal Path, Primal Knowledge* |*3* |*+2*
|*4th* |*+2* |*Ability Score Improvement* |*3* |*+2*
|*5th* |*+3* |*Extra Attack, Fast Movement* |*3* |*+2*
|*6th* |*+3* |*Path Feature* |*4* |*+2*
|*7th* |*+3* |*Feral Instinct, Instinctive Pounce* |*4* |*+2*
|*8th* |*+3* |*Ability Score Improvement* |*4* |*+2*
|*9th* |*+4* |*Brutal Critical (1 die)* |*4* |*+3*
|*10th* |*+4* |*Path feature* |*4* |*+3*
|*11th* |*+4* |*Relentless Rage* |*4* |*+3*
|*12th* |*+4* |*Ability Score Improvement* |*5* |*+3*
|*13th* |*+5* |*Brutal Critical (2 dice)* |*5* |*+3*
|*14th* |*+5* |*Path feature* |*5* |*+3*
|*15th* |*+5* |*Persistent Rage* |*5* |*+3*
|*16th* |*+5* |*Ability Score Improvement* |*5* |*+4*
|*17th* |*+6* |*Brutal Critical (3 dice)* |*6* |*+4*
|*18th* |*+6* |*Indomitable Might* |*6* |*+4*
|*19th* |*+6* |*Ability Score Improvement* |*6* |*+4*
|*20th* |*+6* |*Primal Champion* |*Unlimited* |*+4*
|===

[width="99%"]
|===
|
*Hit Points*

*_Hit Dice_:* 1d12

*_Hit Points at 1st Level:_* 12 + your Constitution modifier

*_Hit Points at Higher Levels:_* 1d12 (or 7) + your Constitution
modifier per Barbarian level after 1st
|
*Proficiencies*

*_Armor:_* light armor, medium armor, shields

*_Weapons_:* simple weapons, martial weapons

*_Tools_:* none

*_Saving Throws_:* Strength, Constitution

*_Skills_:* Choose 2 from Animal Handling, Athletics, Intimidation,
Nature, Perception, and Survival.
a|
*Starting Equipment*

You start with the following items, plus anything provided by your
background.

* {blank}
+
____
{empty}(a) a greataxe or (b) any martial melee weapon
____
* {blank}
+
____
{empty}(a) two handaxes or (b) any simple weapon
____
* {blank}
+
____
An explorer's pack, and four javelins
____
|===

=== *Rage*

In battle, you fight with primal ferocity. On your turn, you can enter a
rage as a bonus action.

While raging, you gain the following benefits if you aren't wearing
heavy armor:

You have advantage on Strength checks and Strength saving throws.

When you make a melee weapon attack using Strength, you gain a +2 bonus
to the damage roll. This bonus increases as you level.

You have resistance to bludgeoning, piercing, and slashing damage.

If you are able to cast spells, you can't cast them or concentrate on
them while raging.

Your rage lasts for 1 minute. It ends early if you are knocked
unconscious or if your turn ends and you haven't attacked a hostile
creature since your last turn or taken damage since then. You can also
end your rage on your turn as a bonus action.

Once you have raged the maximum number of times for your barbarian
level, you must finish a long rest before you can rage again. You may
rage 2 times at 1st level, 3 at 3rd, 4 at 6th, 5 at 12th, and 6 at 17th.

=== *Unarmored Defense*

While you are not wearing any armor, your Armor Class equals 10 + your
Dexterity modifier + your Constitution modifier. You can use a shield
and still gain this benefit.

=== *Danger Sense*

At 2nd level, you gain an uncanny sense of when things nearby aren't as
they should be, giving you an edge when you dodge away from danger. You
have advantage on Dexterity saving throws against effects that you can
see, such as traps and spells. To gain this benefit, you can't be
blinded, deafened, or incapacitated.

=== *Reckless Attack*

Starting at 2nd level, you can throw aside all concern for defense to
attack with fierce desperation. When you make your first attack on your
turn, you can decide to attack recklessly. Doing so gives you advantage
on melee weapon attack rolls using Strength during this turn, but attack
rolls against you have advantage until your next turn.

=== *Primal Path*

At 3rd level, you choose a path that shapes the nature of your rage from
the list of available paths. Your choice grants you features at 3rd
level and again at 6th, 10th, and 14th levels.

=== *Primal Knowledge*

3rd-level barbarian optional feature

When you reach 3rd level and again at 10th level, you gain proficiency
in one skill of your choice from the list of skills available to
barbarians at 1st level.

=== *Ability Score Improvement*

When you reach 4th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Extra Attack*

Beginning at 5th level, you can attack twice, instead of once, whenever
you take the Attack action on your turn.

=== *Fast Movement*

Starting at 5th level, your speed increases by 10 feet while you aren't
wearing heavy armor.

=== *Path Feature*

At 6th level, you gain a feature from your Primal Path.

=== *Feral Instinct*

By 7th level, your instincts are so honed that you have advantage on
initiative rolls.

Additionally, if you are surprised at the beginning of combat and aren't
incapacitated, you can act normally on your first turn, but only if you
enter your rage before doing anything else on that turn.

=== *Instinctive Pounce*

7th-level barbarian optional feature

As part of the bonus action you take to enter your rage, you can move up
to half your speed.

=== *Ability Score Improvement*

When you reach 8th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Brutal Critical (1 die)*

Beginning at 9th level, you can roll one additional weapon damage die
when determining the extra damage for a critical hit with a melee
attack.

This increases to two additional dice at 13th level and three additional
dice at 17th level.

=== *Path feature*

At 10th level, you gain a feature from your Primal Path.

=== *Relentless Rage*

Starting at 11th level, your rage can keep you fighting despite grievous
wounds. If you drop to 0 hit points while you're raging and don't die
outright, you can make a DC 10 Constitution saving throw. If you
succeed, you drop to 1 hit point instead.

Each time you use this feature after the first, the DC increases by 5.
When you finish a short or long rest, the DC resets to 10.

=== *Ability Score Improvement*

When you reach 12th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Brutal Critical (2 dice)*

At 13th level, you can roll two additional weapon damage dice when
determining the extra damage for a critical hit with a melee attack.

This increases to three additional dice at 17th level.

=== *Path feature*

At 14th level, you gain a feature from your Primal Path.

=== *Persistent Rage*

Beginning at 15th level, your rage is so fierce that it ends early only
if you fall unconscious or if you choose to end it.

=== *Ability Score Improvement*

When you reach 16th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Brutal Critical (3 dice)*

At 17th level, you can roll three additional weapon damage dice when
determining the extra damage for a critical hit with a melee attack.

=== *Indomitable Might*

Beginning at 18th level, if your total for a Strength check is less than
your Strength score, you can use that score in place of the total.

=== *Ability Score Improvement*

When you reach 19th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Primal Champion*

At 20th level, you embody the power of the wilds. Your Strength and
Constitution scores increase by 4. Your maximum for those scores is now
24.

include::barbarian_subclass.adoc[]

