== *Barbarian Paths*

=== Path of the Ancestral Guardian

Some barbarians hail from cultures that revere their ancestors. These
tribes teach that the warriors of the past linger in the world as mighty
spirits, who can guide and protect the living. When a barbarian who
follows this path rages, the barbarian contacts the spirit world and
calls on these guardian spirits for aid.

Barbarians who draw on their ancestral guardians can better fight to
protect their tribes and their allies. In order to cement ties to their
ancestral guardians, barbarians who follow this path cover themselves in
elaborate tattoos that celebrate their ancestors' deeds. These tattoos
tell sagas of victories against terrible monsters and other fearsome
rivals.

==== *4TH LEVEL: Ancestral Protectors*

Starting when you choose this path at 3rd level, spectral warriors
appear when you enter your rage. While you're raging, the first creature
you hit with an attack on your turn becomes the target of the warriors,
which hinder its attacks. Until the start of your next turn, that target
has disadvantage on any attack roll that isn't against you, and when the
target hits a creature other than you with an attack, that creature has
resistance to the damage dealt by the attack. The effect on the target
ends early if your rage ends.

==== *6TH LEVEL: Spirit Shield*

Beginning at 6th level, the guardian spirits that aid you can provide
supernatural protection to those you defend. If you are raging and
another creature you can see within 30 feet of you takes damage, you can
use your reaction to reduce that damage by 2d6.

When you reach certain levels in this class, you can reduce the damage
by more: by 3d6 at 10th level and by 4d6 at 14th level.

==== *10TH LEVEL: Consult the Spirits*

At 10th level, you gain the ability to consult with your ancestral
spirits. When you do so, you cast the augury or clairvoyance spell,
without using a spell slot or material components. Rather than creating
a spherical sensor, this use of clairvoyance invisibly summons one of
your ancestral spirits to the chosen location. Wisdom is your
spellcasting ability for these spells.

After you cast either spell in this way, you can't use this feature
again until you finish a short or long rest.

==== *14TH LEVEL: Vengeful Ancestors*

At 14th level, your ancestral spirits grow powerful enough to retaliate.
When you use your Spirit Shield to reduce the damage of an attack, the
attacker takes an amount of force damage equal to the damage that your
Spirit Shield prevents.

=== Path of the Berserker

For some barbarians, rage is a means to an end—that end being violence.
The Path of the Berserker is a path of untrammeled fury. As you enter
the berserker’s rage, you thrill in the chaos of battle.

==== *3RD LEVEL: Frenzy*

You can go into a frenzy in battle. If you use Reckless Attack while
your Rage is active, you deal extra damage to the first target you hit
on your turn with a Strength-based attack. To determine the extra
damage, roll a number of d6s equal to your Rage Damage bonus, and add
them together. The damage has the same type as the weapon or Unarmed
Strike used for the attack.

==== *6TH LEVEL: Mindless Rage*

You have immunity to the Charmed and Frightened conditions while your
Rage is active. If you are Charmed or Frightened when you enter your
Rage, that condition ends on you.

==== *10TH LEVEL: Retaliation*

When you take damage from a creature that is within 5 feet of you, you
can use your Reaction to make one melee attack against that creature,
using a weapon or an Unarmed Strike.

==== *14TH LEVEL: Intimidating Presence*

Instead of one of your attacks, you can strike terror into others with
your menacing presence, as you swell with primal power. When you do so,
each creature of your choice within 30 feet of you—or 60 feet of you if
your Rage is active—must make a Wisdom saving throw (DC equal to 8 +
your proficiency bonus + your Strength modifier), provided the creature
isn’t behind Total Cover. On a failed save, a creature has the
Frightened condition for 1 minute. At the end of each of the Frightened
creature’s turns, the creature repeats the saving throw, ending the
effect on itself on a successful save.

Once you use this feature, you can’t use it again until you finish a
Long Rest. If you’ve run out of

uses of this feature, you can expend a use of your Rage, choosing not to
activate the Rage and

activating Intimidating Presence instead.

=== Path of the Totem Warrior

The Path of the Totem Warrior is a spiritual journey, as the barbarian
accepts a spirit animal as guide, protector, and inspiration. In battle,
your totem spirit fills you with supernatural might, adding magical fuel
to your barbarian rage.

Most barbarian tribes consider a totem animal to be kin to a particular
clan. In such cases, it is unusual for an individual to have more than
one totem animal spirit, though exceptions exist.

==== *3RD LEVEL: Spirit Seeker*

Yours is a path that seeks attunement with the natural world, giving you
a kinship with beasts. At 3rd level when you adopt this path, you gain
the ability to cast the beast sense and speak with animals spells, but
only as rituals, as described in chapter 10.

==== *3RD LEVEL: Totem Spirit*

At 3rd level, when you adopt this path, you choose a totem spirit and
gain its feature. You must make or acquire a physical totem object—an
amulet or similar adornment—that incorporates fur or feathers, claws,
teeth, or bones of the totem animal. At your option, you also gain minor
physical attributes that are reminiscent of your totem spirit. For
example, if you have a bear totem spirit, you might be unusually hairy
and thick-skinned, or if your totem is the eagle, your eyes turn bright
yellow.

Your totem animal might be an animal related to those listed here but
more appropriate to your homeland. For example, you could choose a hawk
or vulture in place of an eagle.

*_Bear._*

While raging, at the start of your turn you gain temporary hit points to
equal your Constitution mod + your barbarian level. The spirit of the
bear makes you tough enough to stand up to any punishment.

*_Eagle._*

While you're raging and aren't wearing heavy armor, other creatures have
disadvantage on opportunity attack rolls against you, and you can use
the Dash action as a bonus action on your turn. The spirit of the eagle
makes you into a predator who can weave through the fray with ease.

*_Elk._*

While you're raging and aren't wearing heavy armor, your walking speed
increases by 15 feet. The spirit of the elk makes you extraordinarily
swift.

*_Tiger._*

While raging, you can add 10 feet to your long jump distance and 3 feet
to your high jump distance. The spirit of the tiger empowers your leaps.

*_Wolf._*

While you're raging, your friends have advantage on melee attack rolls
against any creature within 5 feet of you that is hostile to you. The
spirit of the wolf makes you a leader of hunters.

==== *6TH LEVEL: Aspect of the Beast*

At 6th level, you gain a magical benefit based on the totem animal of
your choice. You can choose the same animal you selected at 3rd level or
a different one.

*_Bear._*

You gain the might of a bear. Your carrying capacity (including maximum
load and maximum lift) is doubled, and you have advantage on Strength
checks made to push, pull, lift, or break objects.

*_Eagle._*

You gain the eyesight of an eagle. You can see up to 1 mile away with no
difficulty, able to discern even fine details as though looking at
something no more than 100 feet away from you. Additionally, dim light
doesn't impose disadvantage on your Wisdom (Perception) checks.

*_Elk._*

Whether mounted or on foot, your travel pace is doubled, as is the
travel pace of up to ten companions while they're within 60 feet of you
and you're not incapacitated. The elk spirit helps you roam far and
fast.

*_Tiger._*

You gain proficiency in two skills from the following list: Athletics,
Acrobatics, Stealth, and Survival. The cat spirit hones your survival
instincts.

*_Wolf._*

You gain the hunting sensibilities of a wolf. You can track other
creatures while traveling at a fast pace, and you can move stealthily
while traveling at a normal pace.

==== *10TH LEVEL: Spirit Walker*

At 10th level, you can cast the commune with nature spell, but only as a
ritual. When you do so, a spiritual version of one of the animals you
chose for Totem Spirit or Aspect of the Beast appears to you to convey
the information you seek.

==== *14TH LEVEL: Totemic Attunement*

At 14th level, you gain a magical benefit based on a totem animal of
your choice. You can choose the same animal you selected previously or a
different one.

*_Bear._*

While you're raging, any creature within 5 feet of you that's hostile to
you has disadvantage on attack rolls against targets other than you or
another character with this feature. An enemy is immune to this effect
if it can't see or hear you or if it can't be frightened.

*_Eagle._*

While raging, you have a flying speed equal to your current walking
speed. This benefit works only in short bursts; you fall if you end your
turn in the air and nothing else is holding you aloft.

*_Elk._*

While raging, you can use a bonus action during your move to pass
through the space of a Large or smaller creature. That creature must
succeed on a Strength saving throw (DC 8 + your Strength bonus + your
proficiency bonus) or be knocked prone and take bludgeoning damage equal
to 1d12 + your Strength modifier.

*_Tiger._*

While you're raging, if you move at least 20 feet in a straight line
toward a Large or smaller target right before making a melee weapon
attack against it, you can use a bonus action to make an additional
melee weapon attack against it.

*_Wolf._*

While you're raging, you can use a bonus action on your turn to knock a
Large or smaller creature prone when you hit it with a melee weapon
attack.
