== *Druid Circles*

=== Circle of the Land

The Circle of the Land is made up of mystics and sages who safeguard
ancient knowledge and rites through a vast oral tradition. These druids
meet within sacred circles of trees or standing stones to whisper primal
secrets in Druidic.

The circle's wisest members preside as the chief priests of communities
that hold to the Old Faith and serve as advisors to the rulers of those
folk. As a member of this circle, your magic is influenced by the land
where you were initiated into the circle's mysterious rites.

==== 2nd LEVEL: Bonus Cantrip

You learn one additional druid cantrip of your choice. This cantrip
doesn't count against the number of druid cantrips you know.

==== 2nd LEVEL: Natural Recovery

Starting at 2nd level, you can regain some of your magical energy by
sitting in meditation and communing with nature. During a short rest,
you choose expended spell slots to recover. The spell slots can have a
combined level that is equal to or less than half your druid level
(rounded up), and none of the slots can be 6th level or higher. You
can't use this feature again until you finish a long rest.

For example, when you are a 4th-level druid, you can recover up to two
levels worth of spell slots. You can recover either a 2nd-level slot or
two 1st-level slots.

==== 2nd LEVEL: Circle Spells

Your mystical connection to the land infuses you with the ability to
cast certain spells. At 3rd, 5th, 7th, and 9th level you gain access to
circle spells connected to the land where you became a druid. Choose
that land—arctic, coast, desert, forest, grassland, mountain, swamp, or
Underdark—and consult the associated list of spells.

Once you gain access to a circle spell, you always have it prepared, and
it doesn't count against the number of spells you can prepare each day.
If you gain access to a spell that doesn't appear on the druid spell
list, the spell is nonetheless a druid spell for you.

*Artic*

[width="100%",cols="14%,86%",options="header",]
|===
|*Druid Level* |*Circle Spells*
|3rd |https://5e.tools/spells.html#hold person_phb,
https://5e.tools/spells.html#spike growth_phb

|5th |https://5e.tools/spells.html#sleet storm_phb,
https://5e.tools/spells.html#slow_phb

|7th |https://5e.tools/spells.html#freedom of movement_phb,
https://5e.tools/spells.html#ice storm_phb

|9th |https://5e.tools/spells.html#commune with nature_phb,
https://5e.tools/spells.html#cone of cold_phb
|===

*Coast*

[width="100%",cols="14%,86%",options="header",]
|===
|*Druid Level* |*Circle Spells*
|3rd |https://5e.tools/spells.html#mirror image_phb,
https://5e.tools/spells.html#misty step_phb

|5th |https://5e.tools/spells.html#water breathing_phb,
https://5e.tools/spells.html#water walk_phb

|7th |https://5e.tools/spells.html#control water_phb,
https://5e.tools/spells.html#freedom of movement_phb

|9th |https://5e.tools/spells.html#conjure elemental_phb,
https://5e.tools/spells.html#scrying_phb
|===

*Desert*

[width="100%",cols="14%,86%",options="header",]
|===
|*Druid Level* |*Circle Spells*
|3rd |https://5e.tools/spells.html#blur_phb,
https://5e.tools/spells.html#silence_phb

|5th |https://5e.tools/spells.html#create food and water_phb,
https://5e.tools/spells.html#protection from energy_phb

|7th |https://5e.tools/spells.html#blight_phb,
https://5e.tools/spells.html#hallucinatory terrain_phb

|9th |https://5e.tools/spells.html#insect plague_phb,
https://5e.tools/spells.html#wall of stone_phb
|===

*Forest*

[width="100%",cols="14%,86%",options="header",]
|===
|*Druid Level* |*Circle Spells*
|3rd |https://5e.tools/spells.html#barkskin_phb,
https://5e.tools/spells.html#spider climb_phb

|5th |https://5e.tools/spells.html#call lightning_phb,
https://5e.tools/spells.html#plant growth_phb

|7th |https://5e.tools/spells.html#divination_phb,
https://5e.tools/spells.html#freedom of movement_phb

|9th |https://5e.tools/spells.html#commune with nature_phb,
https://5e.tools/spells.html#tree stride_phb
|===

*Grassland*

[width="100%",cols="14%,86%",options="header",]
|===
|*Druid Level* |*Circle Spells*
|3rd |https://5e.tools/spells.html#invisibility_phb,
https://5e.tools/spells.html#pass without trace_phb

|5th |https://5e.tools/spells.html#daylight_phb,
https://5e.tools/spells.html#haste_phb

|7th |https://5e.tools/spells.html#divination_phb,
https://5e.tools/spells.html#freedom of movement_phb

|9th |https://5e.tools/spells.html#dream_phb,
https://5e.tools/spells.html#insect plague_phb
|===

*Mountain*

[width="100%",cols="14%,86%",options="header",]
|===
|*Druid Level* |*Circle Spells*
|3rd |https://5e.tools/spells.html#spider climb_phb,
https://5e.tools/spells.html#spike growth_phb

|5th |https://5e.tools/spells.html#lightning bolt_phb,
https://5e.tools/spells.html#meld into stone_phb

|7th |https://5e.tools/spells.html#stone shape_phb,
https://5e.tools/spells.html#stoneskin_phb

|9th |https://5e.tools/spells.html#passwall_phb,
https://5e.tools/spells.html#wall of stone_phb
|===

*Swamp*

[width="100%",cols="14%,86%",options="header",]
|===
|*Druid Level* |*Circle Spells*
|3rd |https://5e.tools/spells.html#darkness_phb,
https://5e.tools/spells.html#melf's acid arrow_phb

|5th |https://5e.tools/spells.html#water walk_phb,
https://5e.tools/spells.html#stinking cloud_phb

|7th |https://5e.tools/spells.html#freedom of movement_phb,
https://5e.tools/spells.html#locate creature_phb

|9th |https://5e.tools/spells.html#insect plague_phb,
https://5e.tools/spells.html#scrying_phb
|===

*Underdark*

[width="100%",cols="14%,86%",options="header",]
|===
|*Druid Level* |*Circle Spells*
|3rd |https://5e.tools/spells.html#spider climb_phb,
https://5e.tools/spells.html#web_phb

|5th |https://5e.tools/spells.html#gaseous form_phb,
https://5e.tools/spells.html#stinking cloud_phb

|7th |https://5e.tools/spells.html#greater invisibility_phb,
https://5e.tools/spells.html#stone shape_phb

|9th |https://5e.tools/spells.html#cloudkill_phb,
https://5e.tools/spells.html#insect plague_phb
|===

==== 6th LEVEL: Land's Stride

Starting at 6th level, moving through nonmagical difficult terrain costs
you no extra movement. You can also pass through nonmagical plants
without being slowed by them and without taking damage from them if they
have thorns, spines, or a similar hazard.

In addition, you have advantage on saving throws against plants that are
magically created or manipulated to impede movement, such as those
created by the entangle spell.

==== 10th LEVEL: Nature's Ward

When you reach 10th level, you can't be charmed or frightened by
elementals or fey, and you are immune to poison and disease.

==== 14th LEVEL: Nature's Sanctuary

When you reach 14th level, creatures of the natural world sense your
connection to nature and become hesitant to attack you. When a beast or
plant creature attacks you, that creature must make a Wisdom saving
throw against your druid spell save DC. On a failed save, the creature
must choose a different target, or the attack automatically misses. On a
successful save, the creature is immune to this effect for 24 hours.

The creature is aware of this effect before it makes its attack against
you.

=== Circle of the Moon

Druids of the Circle of the Moon are fierce guardians of the wilds.
Their order gathers under the full moon to share news and trade
warnings. They haunt the deepest parts of the wilderness, where they
might go for weeks on end before crossing paths with another humanoid
creature, let alone another druid.

Changeable as the moon, a druid of this circle might prowl as a great
cat one night, soar over the treetops as an eagle the next day, and
crash through the undergrowth in bear form to drive off a trespassing
monster. The wild is in the druid's blood.

==== 2nd LEVEL: Combat Wild Shape

You gain the ability to use Wild Shape on your turn as a bonus action,
rather than as an action.

Additionally, while you are transformed by Wild Shape, you can use a
bonus action to expend one spell slot to regain 1d8 hit points per level
of the spell slot expended.

==== 2nd LEVEL: Circle Forms

The rites of your circle grant you the ability to transform into more
dangerous animal forms. Starting at 2nd level, when you gain a trait
given by this subclass, you can learn one additional Animalistic
Invocation that you are capable of.

==== 6th LEVEL: Primal Strike

Starting at 6th level, your attacks in beast form count as magical for
the purpose of overcoming resistance and immunity to non magical attacks
and damage.

==== 10th LEVEL: Elemental Wild Shape

At 10th level, you learn how to infuse your Wildshape with elemental
magic, you learn the following Animalistic Invocations, you can use only
one of them when you transform.

* {blank}
+
____
Air. fly 90 ft. (hover); *Damage Resistances:* lightning, thunder;
bludgeoning, piercing, and slashing from non magical attacks; *Damage
Immunities* poison
____
* {blank}
+
____
Earth. burrow 30 ft; *Damage Resistances:* bludgeoning, piercing, and
slashing from non magical attacks; *Damage Immunities:* poison
____
* {blank}
+
____
Fire. *Damage Resistances:* bludgeoning, piercing, and slashing from non
magical attacks; *Damage Immunities:* fire, poison; *Action: _Touch._*
_Melee Attack:_ your Spell Attack Modifier to hit, reach 5 ft., one
target. _Hit:_ 2d10 + your Wisdom modifier fire damage. If the target is
a creature or a flammable object, it ignites. Until a creature takes an
action to douse the fire, the target takes 5 (1d12) fire damage at the
start of each of its turns.
____
* {blank}
+
____
Water. swim 90 ft.; *Damage Resistances:* acid; bludgeoning, piercing,
and slashing from non magical attacks; *Damage Immunities:* poison
____

==== 14th LEVEL: Thousand Forms

By 14th level, you have learned to use magic to alter your physical form
in more subtle ways. You can cast the alter self spell at will.

=== Circle of Stars

The Circle of Stars allows druids to draw on the power of starlight.
These druids have tracked heavenly patterns since time immemorial,
discovering secrets hidden amid the constellations. By revealing and
understanding these secrets, the Circle of the Stars seeks to harness
the powers of the cosmos.

Many druids of this circle keep records of the constellations and the
stars' effects on the world. Some groups document these observations at
megalithic sites, which serve as enigmatic libraries of lore. These
repositories might take the form of stone circles, pyramids,
petroglyphs, and underground temples-any construction durable enough to
protect the circle's sacred knowledge even against a great cataclysm.

==== 2nd LEVEL: Star Map

You've created a star chart as part of your heavenly studies. It is a
Tiny object and can serve as a spellcasting focus for your druid spells.
You determine its form by rolling on the Star Map table or by choosing
one.

*Star Map*

[width="100%",cols="6%,94%",options="header",]
|===
|*d6* |*Map Form*
|1 |A scroll covered with depictions of constellations
|2 |A stone tablet with fine holes drilled through it
|3 |A speckled owlbear hide, tooled with raised marks
|4 |A collection of maps bound in an ebony cover
|5 |A crystal that projects starry patterns when placed before a light
|6 |Glass disks that depict constellations
|===

While holding this map, you have these benefits:

* {blank}
+
____
You know the
https://5e.tools/spells.html#guidance_phb[[.underline]#guidance#]
cantrip.
____
* {blank}
+
____
You have the
https://5e.tools/spells.html#guiding%20bolt_phb[[.underline]#guiding
bolt#] spell prepared. It counts as a druid spell for you, and it
doesn't count against the number of spells you can have prepared.
____

If you lose the map, you can perform a 1-hour ceremony to magically
create a replacement. This ceremony can be performed during a short or
long rest, and it destroys the previous map.

==== 2nd LEVEL: Starry Form

As a bonus action, you can expend a use of your Wild Shape feature to
take on a starry form, rather than transforming into a beast.

While in your starry form, you retain your game statistics, but your
body becomes luminous; your joints glimmer like stars, and glowing lines
connect them as on a star chart. This form sheds bright light in a
10-foot radius and dim light for an additional 10 feet. The form lasts
for 10 minutes. It ends early if you dismiss it (no action required),
are incapacitated, die, or use this feature again.

Whenever you assume your starry form, choose which of the following
constellations glimmers on your body; your choice gives you certain
benefits while in the form:

*_Archer._*

A constellation of an archer appears on you. When you activate this
form, and as a bonus action on your subsequent turns while it lasts, you
can make a ranged spell attack, hurling a luminous arrow that targets
one creature within 60 feet of you. On a hit, the attack deals radiant
damage equal to 1d8 + your Wisdom modifier.

*_Chalice._*

A constellation of a life-giving goblet appears on you. Whenever you
cast a spell using a spell slot that restores hit points to a creature,
you or another creature within 30 feet of you can regain hit points
equal to 1d8 + your Wisdom modifier.

*_Dragon._*

A constellation of a wise dragon appears on you. When you make an
Intelligence or a Wisdom check or a Constitution saving throw to
maintain concentration on a spell, you can treat a roll of 9 or lower on
the d20 as a 10.

==== 6th LEVEL: Cosmic Omen

Whenever you finish a long rest, you can consult your Star Map for
omens. When you do so, roll a die. Until you finish your next long rest,
you gain access to a special reaction based on whether you rolled an
even or an odd number on the die:

* {blank}
+
____
*Weal (even).* Whenever a creature you can see within 30 feet of you is
about to make an attack roll, a saving throw, or an ability check, you
can use your reaction to roll a d6 and add the number rolled to the
total.
____
* {blank}
+
____
*Woe (odd).* Whenever a creature you can see within 30 feet of you is
about to make an attack roll, a saving throw, or an ability check, you
can use your reaction to roll a d6 and subtract the number rolled from
the total.
____

You can use this reaction a number of times equal to your proficiency
bonus, and you regain all expended uses when you finish a long rest.

==== 10th LEVEL: Twinkling Constellations

The constellations of your Starry Form improve. The 1d8 of the Archer
and the Chalice becomes 2d8, and while the Dragon is active, you have a
flying speed of 20 feet and can hover.

Moreover, at the start of each of your turns while in your Starry Form,
you can change which constellation glimmers on your body.

==== 14th LEVEL: Full of Stars

While in your Starry Form, you become partially incorporeal, giving you
resistance to bludgeoning, piercing, and slashing damage.

