== *Monk Ways*

=== Way of the Astral Self

A monk who follows the Way of the Astral Self believes their body is an
illusion. They see their ki as a representation of their true form, an
astral self. This astral self has the capacity to be a force of order or
disorder, with some monasteries training students to use their power to
protect the weak and other instructing aspirants in how to manifest
their true selves in service to the mighty.

*Forms of Your Astral Self*

The astral self is a translucent embodiment of the monk's soul. As a
result, an astral self can reflect aspects of a monk's background,
ideals, flaws, and bonds, and an astral self doesn't necessarily look
anything like the monk. For example, the astral self of a lanky human
might be reminiscent of a minotaur-the strength of which the monk feels
within. Similarly, an orc monk might manifest gossamer arms and a
delicate visage, representing the gentle beauty of the orc's soul. Each
astral self is unique, and some of the monks of this monastic tradition
are known more for the appearance of their astral self than for their
physical appearance.

When choosing this path, consider the quirks that define your monk. Are
you obsessed with something? Are you driven by justice or a selfish
desire? Any of these motivations could manifest in the form of your
astral self.

==== *3RD LEVEL: Arms of the Astral Self*

Your mastery of your ki allows you to summon a portion of your astral
self. As a bonus action, you can spend 1 ki point to summon the arms of
your astral self. When you do so, each creature of your choice that you
can see within 10 feet of you must succeed on a Dexterity saving throw
or take force damage equal to two rolls of your Martial Arts die.

For 10 minutes, these spectral arms hover near your shoulders or
surround your arms (your choice). You determine the arms' appearance,
and they vanish early if you are incapacitated or die.

While the spectral arms are present, you gain the following benefits:

* {blank}
+
____
You can use your Wisdom modifier in place of your Strength modifier when
making Strength checks and Strength saving throws.
____
* {blank}
+
____
You can use the spectral arms to make unarmed strikes.
____
* {blank}
+
____
When you make an unarmed strike with the arms on your turn, your reach
for it is 5 feet greater than normal.
____
* {blank}
+
____
The unarmed strikes you make with the arms can use your Wisdom modifier
in place of your Strength or Dexterity modifier for the attack and
damage rolls, and their damage type is force.
____

==== *6TH LEVEL: Visage of the Astral Self*

You can summon the visage of your astral self. As a bonus action, or as
part of the bonus action you take to activate Arms of the Astral Self,
you can spend 1 ki point to summon this visage for 10 minutes. It
vanishes early if you are incapacitated or die.

The spectral visage covers your face like a helmet or mask. You
determine its appearance.

While the spectral visage is present, you gain the following benefits.

*_Astral Sight._*

You can see normally in darkness, both magical and nonmagical, to a
distance of 120 feet.

*_Wisdom of the Spirit._*

You have advantage on Wisdom (Insight) and Charisma (Intimidation)
checks.

*_Word of the Spirit._*

When you speak, you can direct your words to a creature of your choice
that you can see within 60 feet of you, making it so only that creature
can hear you. Alternatively, you can amplify your voice so that all
creatures within 600 feet can hear you.

==== *11TH LEVEL: Body of the Astral Self*

When you have both your astral arms and visage summoned, you can cause
the body of your astral self to appear (no action required). This
spectral body covers your physical form like a suit of armor, connecting
with the arms and visage. You determine its appearance.

While the spectral body is present, you gain the following benefits.

*_Deflect Energy._*

When you take acid, cold, fire, force, lightning, or thunder damage, you
can use your reaction to deflect it. When you do so, the damage you take
is reduced by 1d10 + your Wisdom modifier (minimum reduction of 1).

*_Empowered Arms._*

Once on each of your turns when you hit a target with the Arms of the
Astral Self, you can deal extra damage to the target equal to your
Martial Arts die.

==== *17TH LEVEL: Awakened Astral Self*

Your connection to your astral self is complete, allowing you to unleash
its full potential. As a bonus action, you can spend 5 ki points to
summon the arms, visage, and body of your astral self and awaken it for
10 minutes. This awakening ends early if you are incapacitated or die.

While your astral self is awakened, you gain the following benefits.

*_Armor of the Spirit._*

You gain a +2 bonus to Armor Class.

*_Astral Barrage._*

Whenever you use the Extra Attack feature to attack twice, you can
instead attack three times if all the attacks are made with your astral
arms.

=== *Way of the Four Elements*

You follow a monastic tradition that teaches you to harness the
elements. When you focus your ki, you can align yourself with the forces
of creation and bend the four elements to your will, using them as an
extension of your body. Some members of this tradition dedicate
themselves to a single element, but others weave the elements together.

Many monks of this tradition tattoo their bodies with representations of
their ki powers, commonly imagined as coiling dragons, but also as
phoenixes, fish, plants, mountains, and cresting waves.

==== *3RD LEVEL: Disciple of the Element*

When you reach a Monastic Tradition you learn a new way to improve your
use of the Elements, starting at 3rd level you choose an element and
gain a cantrip, additionally you gain the trait related to that given
element. Whenever you gain a Monastic Tradition in this subclass and
pick an element that you hadn’t you gain the cantrip related to that
element.

*Discipline of Elements Table*

[width="100%",cols="41%,59%",options="header",]
|===
|*_Element_* |*_Cantrip_*
|Earth |_Mold Earth_
|Air |_Gust_
|Fire |_Control Flames_
|Water |_Shape Water_
|===

*Air*. When you hit an Unarmed Strike as part of your Attack action you
can spend 1 ki point to push a creature Large or smaller up to 10 ft,
additionally you can spend 1 ki point to make the creature fall prone.

*Water*. When you use Flurry of flows, and you hit, you can spend 1 ki
point to lose 10 ft of movement to the target. This ki point is used
only once per flurry of blows but can work on both attacks if you use it
with the first hit.

*Earth.* As a part of your Flurry of Blows, instead of one of your
attacks, you can spend up to 3 ki points to give someone you touch
temporary hit points equal to a roll of the martial die for each ki
point spent + Wis modifier.

*Fire*. When you hit a creature with an unarmed strike, you can spend 1
ki point to deal extra fire damage equal to one roll of your Martial
Arts die + your Wisdom modifier. You can use this feature only once per
turn.

==== *6TH LEVEL: Learner of the Element*

At 6th level, you gain access to a new way of using an element, you can
choose the same element or another.

*Air.* Instead of one of your attacks during the flurry of blows, you
can spend 1 ki point and target a creature up to 60 ft from you, and
make a ranged attack using your wisdom. On a hit the target receives
force damage equal to one roll of your Martial Arts die + your Wisdom
modifier, and the target must succeed on a Strength saving throw or fall
prone on a fail.

*Water.* When you make an Unarmed Strike, once per turn, you can spend 1
ki point and it must succeed on a Constitution saving throw or be
restrained and take two rolls of your Martial art Dice of cold damage,
on a success takes half damage and is not restrained.

*Earth.* As an action, you can spend up to 3 ki points, you choose a
part of the terrain that is 60 ft near you, and make a 10 x ki points
spent feet cubes to make the terrain, difficult terrain.

*Fire.* You gain a new way to attack, you can spent up to 3 ki points
and target a creature that is up to 120 ft to you, making a ranged spell
attack using your Wisdom for the attack, on a hit you deal your Wisdom
modifier + a roll of your Martial art dice for each ki point spent.

==== *11TH LEVEL: Form of the Element*

At 11th level, you gain access to a new way of using an element, you can
choose the same element or another.

*Air.* When you use the Dash Action with your Step of the Wind, you can
spend 1 ki point to gain a flying speed during the next minute.

*Water.* As a bonus action you can summon a watery extension of your
arms spending 2 ki points, for the following 1 minute your Unarmed
Strikes have 10 ft of reach.

*Earth.* You can cover yourself in rock creating an armor, as an action,
you can spend 5 ki points to gain resistance to cold, fire, bludgeoning,
piercing and slashing damage, during 1 minute.

*Fire.* When you use the Dodge Action with your Patient Defense, you can
spend 1 ki point to surround yourself in flames during the next minute,
whenever a melee attack hits you, the source of the attack takes 1d8
fire damage.

==== *17TH LEVEL: Master of the Element*

Depending on how you progress through the subclass you gain only the
first trait or not.

*Master of the Element.* When a trait needs to be used with another monk
trait (such as Flurry of Blows, Step of the Wind or Patient Defense) you
no longer need to spend the extra ki point.

*Avatar (Prerequisite: have access to three different elements).* You
can simultaneously use more than one trait by spending only the cost of
the highest one.

*Elemental Master (Prerequisite: have access to all traits for one given
element).* Whenever you use any of the traits given by this subclass you
can use it without spending ki points a number of times equals to half
your proficiency bonus (rounded down).

=== Way of Mercy

Monks of the Way of Mercy learn to manipulate the life force of others
to bring aid to those in need. They are wandering physicians to the poor
and hurt. However, to those beyond their help, they bring a swift end as
an act of mercy.

Those who follow the Way of Mercy might be members of a religious order,
administering to the needy and making grim choices rooted in reality
rather than idealism. Some might be gentle-voiced healers, beloved by
their communities, while others might be masked bringers of macabre
mercies.

The walkers of this way usually don robes with deep cowls, and they
often conceal their faces with masks, presenting themselves as the
faceless bringers of life and death.

==== *3RD LEVEL: Implements of Mercy*

You gain proficiency in the Insight and Medicine skills, and you gain
proficiency with the herbalism kit.

You also gain a special mask, which you often wear when using the
features of this subclass. You determine its appearance, or generate it
randomly by rolling on the Merciful Mask table.

*Merciful Mask*

[width="100%",cols="19%,81%",options="header",]
|===
|*d6* |*Mask Appearance*
|1 |Raven
|2 |Blank and white
|3 |Crying visage
|4 |Laughing visage
|5 |Skull
|6 |Butterfly
|===

==== *3RD LEVEL: Hand of Healing*

Your mystical touch can mend wounds. As an action, you can spend 1 ki
point to touch a creature and restore a number of hit points equal to a
roll of your Martial Arts die + your Wisdom modifier.

When you use your Flurry of Blows, you can replace one of the unarmed
strikes with a use of this feature without spending a ki point for the
healing.

==== *3RD LEVEL: Hand of Harm*

You use your ki to inflict wounds. When you hit a creature with an
unarmed strike, you can spend 1 ki point to deal extra necrotic damage
equal to one roll of your Martial Arts die + your Wisdom modifier. You
can use this feature only once per turn.

==== *6TH LEVEL: Physician's Touch*

You can administer even greater cures with a touch, and if you feel it's
necessary, you can use your knowledge to cause harm.

When you use Hand of Healing on a creature, you can also end one disease
or one of the following conditions affecting the creature: blinded,
deafened, paralyzed, poisoned, or stunned.

When you use Hand of Harm on a creature, you can subject that creature
to the poisoned condition until the end of your next turn.

==== *11TH LEVEL:Flurry of Healing and Harm*

You can now mete out a flurry of comfort and hurt. When you use Flurry
of Blows, you can now replace each of the unarmed strikes with a use of
your Hand of Healing, without spending ki points for the healing.

In addition, when you make an unarmed strike with Flurry of Blows, you
can use Hand of Harm with that strike without spending the ki point for
Hand of Harm. You can still use Hand of Harm only once per turn.

==== *17TH LEVEL:Hand of Ultimate Mercy*

Your mastery of life energy opens the door to the ultimate mercy. As an
action, you can touch the corpse of a creature that died within the past
24 hours and expend 5 ki points. The creature then returns to life,
regaining a number of hit points equal to 4d10 + your Wisdom modifier.
If the creature died while subject to any of the following conditions,
it revives with them removed: blinded, deafened, paralyzed, poisoned,
and stunned.

Once you use this feature, you can't use it again until you finish a
long rest.

