== *Monk*

[width="100%",cols="8%,6%,62%,7%,6%,11%",options="header",]
|===
|*_Level_* |*_Prof. Bonus_* |*_Features_* |*_Martial Arts_* |*_Ki
Points_* |*_Unarmored Movement_*
|*1st* |*+2* |*Unarmored Defense, Martial Arts* |*1d6* |*—* |*—*

|*2nd* |*+2* |*Ki, Dedicated Weapon, Unarmored Movement* |*1d6* |*2*
|*+10 ft.*

|*3rd* |*+2* |*Deflect Missiles, Monastic Tradition, Ki-Fueled Attack*
|*1d6* |*3* |*+10 ft.*

|*4th* |*+2* |*Ability Score Improvement, Slow Fall, Quickened Healing*
|*1d6* |*4* |*+10 ft.*

|*5th* |*+3* |*Extra Attack, Stunning Strike, Focused Aim* |*1d6* |*5*
|*+10 ft.*

|*6th* |*+3* |*Ki-Empowered Strikes, Monastic Tradition feature* |*1d6*
|*6* |*+15 ft.*

|*7th* |*+3* |*Evasion, Stillness of Mind* |*1d6* |*7* |*+15 ft.*

|*8th* |*+3* |*Ability Score Improvement* |*1d6* |*8* |*+15 ft.*

|*9th* |*+4* |*Unarmored Movement improvement* |*1d6* |*9* |*+15 ft.*

|*10th* |*+4* |*Purity of Body* |*1d6* |*10* |*+20 ft.*

|*11th* |*+4* |*Monastic Tradition feature* |*1d8* |*11* |*+20 ft.*

|*12th* |*+4* |*Ability Score Improvement* |*1d8* |*12* |*+20 ft.*

|*13th* |*+5* |*Tongue of the Sun and Moon* |*1d8* |*13* |*+20 ft.*

|*14th* |*+5* |*Diamond Soul* |*1d8* |*14* |*+25 ft.*

|*15th* |*+5* |*Timeless Body* |*1d8* |*15* |*+25 ft.*

|*16th* |*+5* |*Ability Score Improvement* |*1d8* |*16* |*+25 ft.*

|*17th* |*+6* |*Monastic Tradition feature* |*1d10* |*17* |*+25 ft.*

|*18th* |*+6* |*Empty Body* |*1d10* |*18* |*+30 ft.*

|*19th* |*+6* |*Ability Score Improvement* |*1d10* |*19* |*+30 ft.*

|*20th* |*+6* |*Perfect Self* |*1d10* |*20* |*+30 ft.*
|===

[width="99%"]
|===
|
*Hit Points*

*_Hit Dice_*: 1d8

*_Hit Points at 1st Level_*: 8 + your Constitution modifier

*_Hit Points at Higher Levels_*: 1d8 (or 5) + your Constitution modifier
per Monk level after 1st
|
*Proficiencies*

*_Armor_*: none

*_Weapons_*: simple weapons, shortswords

*_Tools:_* any one type of artisan's tools or any one musical instrument
of your choice

*_Saving Throws_*: Strength, Dexterity

*_Skills_*: Choose 2 from Acrobatics, Athletics, History, Insight,
Religion, and Stealth.
a|
*Starting Equipment*

You start with the following items, plus anything provided by your
background.

* {blank}
+
____
{empty}(a) a shortsword or (b) any simple weapon
____
* {blank}
+
____
{empty}(a) a dungeoneer's pack or (b) an explorer's pack
____
* {blank}
+
____
10 darts
____
|===

=== *Unarmored Defense*

Beginning at 1st level, while you are wearing no armor and not wielding
a shield, your AC equals 10 + your Dexterity modifier + your Wisdom
modifier.

=== *Martial Arts*

Your practice of martial arts gives you mastery of combat styles that
use unarmed strikes and monk weapons, which are shortswords and any
simple melee weapons that don't have the two-handed or heavy property.

You gain the following benefits while you are unarmed or wielding only
monk weapons and you aren't wearing armor or wielding a shield.

* {blank}
+
____
You can use Dexterity instead of Strength for the attack and damage
rolls of your unarmed strikes and monk weapons.
____
* {blank}
+
____
You can roll a d4 in place of the normal damage of your unarmed strike
or monk weapon. This die changes as you gain monk levels, as shown in
the Martial Arts column of the Monk table.
____
* {blank}
+
____
When you use the Attack action with an unarmed strike or a monk weapon
on your turn, you can make one unarmed strike as a bonus action. For
example, if you take the Attack action and attack with a quarterstaff,
you can also make an unarmed strike as a bonus action, assuming you
haven't already taken a bonus action this turn.
____

Certain monasteries use specialized forms of the monk weapons. For
example, you might use a club that is two lengths of wood connected by a
short chain (called a nunchaku) or a sickle with a shorter, straighter
blade (called a kama).

=== *Ki*

Starting at 2nd level, your training allows you to harness the mystic
energy of ki. Your access to this energy is represented by a number of
ki points. Your monk level determines the number of points you have, as
shown in the Ki Points column of the Monk table.

You can spend these points to fuel various ki features. You start
knowing three such features: Flurry of Blows, Patient Defense, and Step
of the Wind. You learn more ki features as you gain levels in this
class.

When you spend a ki point, it is unavailable until you finish a short or
long rest, at the end of which you draw all of your expended ki back
into yourself. You must spend at least 30 minutes of the rest meditating
to regain your ki points.

Some of your ki features require your target to make a saving throw to
resist the feature's effects. The saving throw DC is calculated as
follows:

____
*_Ki save DC_* = 8 + your proficiency bonus + your Wisdom modifier
____

*_Flurry of Blows._*

Immediately after you take the Attack action on your turn, you can spend
1 ki point to make two unarmed strikes as a bonus action.

*_Patient Defense._*

You can spend 1 ki point to take the Dodge action as a bonus action on
your turn.

*_Step of the Wind._*

You can spend 1 ki point to take the Disengage or Dash action as a bonus
action on your turn, and your jump distance is doubled for the turn.

=== *Dedicated Weapon*

You train yourself to use a variety of weapons as monk weapons, not just
simple melee weapons and shortswords. Whenever you finish a short or
long rest, you can touch one weapon, focus your ki on it, and then count
that weapon as a monk weapon until you use this feature again.

The chosen weapon must meet these criteria:

* {blank}
+
____
The weapon must be a
https://5e.tools/items.html#blankhash,flstsource:phb=1,flstcategory:basic=1,flsttype:martial%20weapon=1~simple%20weapon=1,flstproperty:heavy=2~special=2[[.underline]#simple
or martial weapon#].
____
* {blank}
+
____
You must be proficient with it.
____
* {blank}
+
____
It must lack the heavy and special properties.
____

=== *Unarmored Movement*

Starting at 2nd level, your speed increases by 10 feet while you are not
wearing armor or wielding a shield. This bonus increases when you reach
certain monk levels, as shown in the Monk table.

At 9th level, you gain the ability to move along vertical surfaces and
across liquids on your turn without falling during the move.

=== *Deflect Missiles*

Starting at 3rd level, you can use your reaction to deflect or catch the
missile when you are hit by a ranged weapon attack. When you do so, the
damage you take from the attack is reduced by 1d10 + your Dexterity
modifier + your monk level.

If you reduce the damage to 0, you can catch the missile if it is small
enough for you to hold in one hand and you have at least one hand free.
If you catch a missile in this way, you can spend 1 ki point to make a
ranged attack (range 20/60 feet) with the weapon or piece of ammunition
you just caught, as part of the same reaction. You make this attack with
proficiency, regardless of your weapon proficiencies, and the missile
counts as a monk weapon for the attack.

=== *Monastic Tradition*

When you reach 3rd level, you commit yourself to a monastic tradition,
chosen from the list of available traditions. Your tradition grants you
features at 3rd level and again at 6th, 11th, and 17th level.

=== *Ki-Fueled Attack*

If you spend 1 ki point or more as part of your action on your turn, you
can make one attack with an unarmed strike or a monk weapon as a bonus
action before the end of the turn.

=== *Ability Score Improvement*

When you reach 4th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Slow Fall*

Beginning at 4th level, you can use your reaction when you fall to
reduce any falling damage you take by an amount equal to five times your
monk level.

=== *Quickened Healing*

As an action, you can spend 2 ki points and roll a Martial Arts die. You
regain a number of hit points equal to the number rolled plus your
proficiency bonus.

=== *Extra Attack*

Beginning at 5th level, you can attack twice, instead of once, whenever
you take the Attack action on your turn.

=== *Stunning Strike*

Starting at 5th level, you can interfere with the flow of ki in an
opponent's body. When you hit another creature with a melee weapon
attack, you can spend 2 ki points to attempt a stunning strike. The
target must succeed on a Constitution saving throw or be stunned until
the end of your next turn. These attacks must be from your Attack
action.

=== *Focused Aim*

When you miss with an attack roll, you can spend 1 to 3 ki points to
increase your attack roll by 2 for each of these ki points you spend,
potentially turning the miss into a hit.

=== *Ki-Empowered Strikes*

Starting at 6th level, your unarmed strikes count as magical for the
purpose of overcoming resistance and immunity to non magical attacks and
damage.

=== *Monastic Tradition feature*

At 6th level, you gain one feature granted by your Monastic Tradition.

=== *Evasion*

At 7th level, your instinctive agility lets you dodge out of the way of
certain area effects, such as a blue dragon's lightning breath or a
fireball spell. When you are subjected to an effect that allows you to
make a Dexterity saving throw to take only half damage, you instead take
no damage if you succeed on the saving throw, and only half damage if
you fail.

=== *Stillness of Mind*

Starting at 7th level, you can use your action to end one effect on
yourself that is causing you to be charmed or frightened.

=== *Ability Score Improvement*

When you reach 8th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Unarmored Movement improvement*

At 9th level, you gain the ability to move along vertical surfaces and
across liquids on your turn without falling during the move.

=== *Purity of Body*

At 10th level, your mastery of the ki flowing through you makes you
immune to disease and poison.

=== *Monastic Tradition feature*

At 11th level, you gain one feature granted by your Monastic Tradition.

=== *Ability Score Improvement*

When you reach 12th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Tongue of the Sun and Moon*

Starting at 13th level, you learn to touch the ki of other minds so that
you understand all spoken languages. Moreover, any creature that can
understand a language can understand what you say.

=== *Diamond Soul*

Beginning at 14th level, your mastery of ki grants you proficiency in
all saving throws.

Additionally, whenever you make a saving throw and fail, you can spend 1
ki point to reroll it and take the second result.

=== *Timeless Body*

At 15th level, your ki sustains you so that you suffer none of the
frailty of old age, and you can't be aged magically. You can still die
of old age, however. In addition, you no longer need food or water.

=== *Ability Score Improvement*

When you reach 16th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Monastic Tradition feature*

At 17th level, you gain one feature granted by your Monastic Tradition.

=== *Empty Body*

Beginning at 18th level, you can use your action to spend 4 ki points to
become invisible for 1 minute. During that time, you also have
resistance to all damage but force damage.

Additionally, you can spend 8 ki points to cast the astral projection
spell, without needing material components. When you do so, you can't
take any other creatures with you.

=== *Ability Score Improvement*

When you reach 19th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Perfect Self*

At 20th level, you master the use of your Ki, at the start of your turn
you regain 1 Ki point. This benefit only works during combat, whenever
you roll initiative you regain a number of ki points equal to a roll of
your Martial Art dice plus your Wisdom modifier.

include::monk_subclass.adoc[]
