== *Ranger Conclaves*

=== Fey Wanderer

A fey mystique surrounds you, thanks to the boon of an archfey, the
shining fruit you ate from a talking tree, the magic spring you swam in,
or some other auspicious event. However you acquired your fey magic, you
are now a Fey Wanderer, a ranger who represents both the mortal and the
fey realms. This fey aura comes from your bond with a fey spirit.

==== *3rd LEVEL: Fey Wanderer Magic*

You learn an additional spell when you reach certain levels in this
class, as shown in the Fey Wanderer Spells table. Each spell counts as a
ranger spell for you, but it doesn't count against the number of ranger
spells you know.

_Fey Wanderer Spells_

[width="100%",cols="25%,75%",options="header",]
|===
|*Ranger Level* |*Spells*
|3rd |Charm person
|5th |Misty Step
|9th |Dispel Magic
|13th |Dimension Door
|17th |Mislead
|===

You also possess a preternatural blessing from a fey ally or a place of
fey power. Choose your blessing from the Feywild Gifts table or
determine it randomly.

_Feywild Gifts_

[width="100%",cols="6%,94%",options="header",]
|===
|*d6* |*Gift*
|1 |Illusory butterflies flutter around you while you take a short or
long rest.

|2 |Fresh, seasonal flowers sprout from your hair each dawn.

|3 |You faintly smell of cinnamon, lavender, nutmeg, or another
comforting herb or spice.

|4 |Your shadow dances while no one is looking directly at it.

|5 |Horns or antlers sprout from your head.

|6 |Your skin and hair change color to match the season at each dawn.
|===

==== *3rd LEVEL: Channel Nature*

Your Conclave gives you the following two Channel Nature options.

*Dreadful Strikes.* As a bonus action, you can augment your weapon
strikes with mind-scarring magic, drawn from the gloomy hollows of the
Feywild. During a minute you deal extra 1d6 psychic damage with your
weapons attacks.

*Otherworldly Glamour.* Your fey qualities give you a supernatural
charm. As a result, whenever you make a Charisma check, you can use your
Channel Nature, gaining a bonus to the check equal to your Wisdom
modifier (minimum of +1). This bonus lasts for the next hour.

In addition, you gain proficiency in one of the following skills of your
choice: Deception, Performance, or Persuasion.

==== *7th LEVEL: Beguiling Twist*

The magic of the Feywild guards your mind. You have advantage on saving
throws against being
https://5e.tools/conditionsdiseases.html#charmed_phb[[.underline]#charmed#]
or
https://5e.tools/conditionsdiseases.html#frightened_phb[[.underline]#frightened#].

In addition, whenever you or a creature you can see within 120 feet of
you succeeds on a saving throw against being
https://5e.tools/conditionsdiseases.html#charmed_phb[[.underline]#charmed#]
or
https://5e.tools/conditionsdiseases.html#frightened_phb[[.underline]#frightened#],
you can use your reaction to force a different creature you can see
within 120 feet of you to make a Wisdom saving throw against your spell
save DC. If the save fails, the target is
https://5e.tools/conditionsdiseases.html#charmed_phb[[.underline]#charmed#]
or
https://5e.tools/conditionsdiseases.html#frightened_phb[[.underline]#frightened#]
by you (your choice) for 1 minute. The target can repeat the saving
throw at the end of each of its turns, ending the effect on itself on a
successful save.

==== *11th LEVEL: Fey Reinforcements*

The royal courts of the Feywild have blessed you with the assistance of
fey beings: you know
https://5e.tools/spells.html#summon%20fey_tce[[.underline]#summon fey#].
It doesn't count against the number of ranger spells you know, and you
can cast it without a material component. You can also cast it once
without a spell slot, and you regain the ability to do so when you
finish a long rest.

Whenever you start casting the spell, you can modify it so that it
doesn't require
https://5e.tools/conditionsdiseases.html#concentration_phb[[.underline]#concentration#].
If you do so, the spell's duration becomes 1 minute for that casting.

==== *15th LEVEL: Misty Wanderer*

You can slip in and out of the Feywild to move in a blink of an eye: you
can cast
https://5e.tools/spells.html#misty%20step_phb[[.underline]#misty step#]
without expending a spell slot. You can do so a number of times equal to
your Wisdom modifier (minimum of once), and you regain all expended uses
when you finish a long rest.

In addition, whenever you cast _misty step_, you can bring along one
willing creature you can see within 5 feet of you. That creature
teleports to an unoccupied space of your choice within 5 feet of your
destination space.

=== Shadow Walker

Shadow Walker are at home in the darkest places: deep under the earth,
in gloomy alleyways, in primeval forests, and wherever else the light
dims. In those habitats Shadow Walkers bond themselves with spirits from
the Shadow Realm.

==== 3rd LEVEL: Shadow Walker Magic

Starting at 3rd level, you learn an additional spell when you reach
certain levels in this class, as shown in the *Shadow Walker* Spells
table. The spell counts as a ranger spell for you, but it doesn't count
against the number of ranger spells you know.

Shadow Walker Spells

[width="100%",cols="24%,76%",options="header",]
|===
|*Ranger Level* |*Spells*
|3rd |Disguise self
|5th |Rope trick
|9th |fear
|13th |Greater invisibility
|17th |seeming
|===

==== 3rd LEVEL: Channel Nature

*Dread Ambusher.* When you roll initiative, you can use your Channel
Nature, gaining a bonus to your initiative equals to your Wisdom
modifier. During 1 minute you gain 10 ft to your movement, and if you
take the https://5e.tools/actions.html#attack_phb[[.underline]#Attack#]
action, you can make one additional weapon attack as part of that
action. If that attack hits, the target takes an extra 1d8 necrotic
damage.

*Umbral Sight.* As a bonus action, you can use your Channel Nature,
giving a number of creatures equals to your Wisdom modifier, darkvision
out to a range of 60 feet. If you already have darkvision from your
race, its range increases by 30 feet.

In addition, you are also adept at evading creatures that rely on
darkvision. While in darkness, you are
https://5e.tools/conditionsdiseases.html#invisible_phb[[.underline]#invisible#]
to any creature that relies on darkvision to see you in that darkness.
You gain proficiency in Stealh or Perception, your choice.

==== 7th LEVEL: Iron Mind

By 7th level, you have honed your ability to resist the mind-altering
powers of your prey. You gain proficiency in Wisdom saving throws. If
you already have this proficiency, you instead gain proficiency in
Intelligence or Charisma saving throws (your choice).

==== 11th LEVEL: Stalker's Flurry

At 11th level, you learn to attack with such unexpected speed that you
can turn a miss into another strike. Once on each of your turns when you
miss with a weapon attack, you can make another weapon attack as part of
the same action.

==== 15th LEVEL: Shadowy Dodge

Starting at 15th level, you can dodge in unforeseen ways, with wisps of
supernatural shadow around you. Whenever a creature makes an attack roll
against you and doesn't have advantage on the roll, you can use your
reaction to impose disadvantage on it. You must use this feature before
you know the outcome of the attack roll.

=== Hunter

Hunters have the deepest bond with the beasts, showing themselves by
bonding with a spirit of animal origin.

==== 3rd LEVEL: Hunter Magic

Starting at 3rd level, you learn an additional spell when you reach
certain levels in this class, as shown in the Hunter Spells table. The
spell counts as a ranger spell for you, but it doesn't count against the
number of ranger spells you know.

Hunter Spells

[width="100%",cols="35%,65%",options="header",]
|===
|*Ranger Level* |*Spells*
|3rd |Bless
|5th |Hold Person
|9th |Haste
|13th |Polymorph
|17th |Hold Monster
|===

==== 3rd LEVEL: Hunter Apprentice

At 3rd level, you gain one slot of Hunter Knowledge, you gain additional
slots, when you gain a Conclave feature. You can use those slots to pick
a trait from the given list of that slot. You can change that trait when
you finish a Long Rest of if you use your Channel Nature.

You can use your slot in one of the following traits.

*Colossus Slayer.* Your tenacity can wear down the most potent foes.
When you hit a creature with a weapon attack, the creature takes an
extra 1d8 damage if it's below its hit point maximum. You can deal this
extra damage only once per turn.

*Giant Killer.* When a Large or larger creature within 5 feet of you
hits or misses you with an attack, you can use your reaction to attack
that creature immediately after its attack, provided that you can see
the creature.

*Horde Breaker.* Once on each of your turns when you make a weapon
attack, you can make another attack with the same weapon against a
different creature that is within 5 feet of the original target and
within range of your weapon.

==== 7th LEVEL: Hunter Learner

At 7th level, you gain an additional Hunter Knowledge slot, you can use
it to select one of the following features of your choice.

*Escape the Horde.* Opportunity attacks against you are made with
disadvantage.

*Multiattack Defense.* When a creature hits you with an attack, you gain
a +4 bonus to AC against all subsequent attacks made by that creature
for the rest of the turn.

*Steel Will.* You have advantage on saving throws against being
https://5e.tools/conditionsdiseases.html#frightened_phb[[.underline]#frightened#].

==== 11th LEVEL: Hunter Adept

At 11th level, you gain an additional Hunter Knowledge slot, you can use
it to select one of the following features of your choice.

*Volley.* You can use your action to make a ranged attack against any
number of creatures within 10 feet of a point you can see within your
weapon's range. You must have ammunition for each target, as normal, and
you make a separate attack roll for each target.

*Whirlwind Attack.* You can use your action to make a melee attack
against any number of creatures within 5 feet of you, with a separate
attack roll for each target.

==== 15th LEVEL: Hunter Master

At 15th level, you gain an additional Hunter Knowledge slot, you can use
it to select one of the following features of your choice.

*Evasion.* You can nimbly dodge out of the way of certain area effects,
such as a red dragon's fiery breath or a
https://5e.tools/spells.html#lightning%20bolt_phb[[.underline]#lightning
bolt#] spell. When you are subjected to an effect that allows you to
make a Dexterity saving throw to take only half damage, you instead take
no damage if you succeed on the saving throw, and only half damage if
you fail.

*Stand Against the Tide*. When a hostile creature misses you with a
melee attack, you can use your reaction to force that creature to repeat
the same attack against another creature (other than itself) of your
choice.

*Uncanny Dodge.* When an attacker that you can see hits you with an
attack, you can use your reaction to halve the attack's damage against
you.

=== Ronin

The Ronin are masterless, wandering warriors, beholden to no code but
their own. No two are the same, each with their own tale that led them
down the warrior’s path. They are masters of many weapons, striking with
blade and arrow in a spectacle of blinding speed and accuracy. Some
Ronin use their power to protect the vulnerable—vigilantes doing what
they see as right, no matter the cost. Others pursue their own ends,
unfettered by the consequences of their actions.

Ronin are dangerous combatants, hardened survivors, and above all
things, free.

==== *3rd LEVEL: Ronin Wanderer Magic*

You learn an additional spell when you reach certain levels in this
class, as shown in the Ronin Wanderer Spells table. Each spell counts as
a ranger spell for you, but it doesn't count against the number of
ranger spells you know.

_Ronin Wanderer Spells_

[width="100%",cols="25%,75%",options="header",]
|===
|*Ranger Level* |*Spells*
|3rd |expeditious retreat
|5th |blur
|9th |remove curse
|13th |death ward
|17th |legend lore
|===

==== *3rd LEVEL: Channel Nature*

Your Conclave gives you the following two Channel Nature options.

*Masterless.* As a bonus action, you can use your channel Nature to end
the Charmed or Frightened.

==== *3rd LEVEL: Slash Draw*

You have mastered the art of striking with sudden, explosive power at
any moment. The first time each turn that you hit a creature with a
melee weapon attack using a weapon you drew that turn, the attack deals
an extra 1d6 damage of that weapon’s type. This extra damage increases
to 1d8 when you reach 11th level in this class.

In addition, twice per turn, you can draw or stow one weapon, provided
you aren’t incapacitated (no action required).

==== *7th LEVEL: Cleaving Parry*

When a creature makes a weapon attack against you while you have a
stowed melee weapon and a free hand, you can use your reaction to
attempt to parry that blow, drawing your stowed weapon as you do so.
Your AC increases by an amount equal to your Dexterity or Strength
modifier (your choice) against that attack, and you gain temporary hit
points equal to your proficiency bonus + your Wisdom modifier (minimum
of 1). After the attack hits or misses, you can then stow that weapon as
a part of this reaction.

==== *11th LEVEL: Multi-Weapon Mastery*

You have advantage on the first melee weapon attack you make each turn,
as well as advantage on the first ranged weapon attack you make each
turn.

In addition, being within 5 feet of a hostile creature doesn’t impose
disadvantage on your ranged attack rolls.

==== *15th LEVEL: Relentless Onslaught*

The speed and ferocity of your onslaught is legendary. When you take the
Attack action, each time you score a critical hit or reduce a creature
to 0 hit points as part of that action, you can make one additional
weapon attack. You can make up to three additional attacks with this
feature per turn.

