== *Sorcerer Origin*

=== Aberrant Mind

An alien influence has wrapped its tendrils around your mind, giving you
psionic power. You can now touch other minds with that power and alter
the world around you by using it to control the magical energy of the
multiverse. Will this power shine from you as a hopeful beacon to
others? Or will you be a source of terror to those who feel the stab of
your mind and witness the strange manifestations of your might?

As an Aberrant Mind sorcerer, you decide how you acquired your powers.
Were you born with them? Or did an event later in life leave you shining
with psionic awareness? Consult the Aberrant Origins table for a
possible origin of your power.

*Aberrant Origins*

[width="100%",cols="6%,94%",options="header",]
|===
|*d6* |*Origin*
|1 |You were exposed to the Far Realm's warping influence. You are
convinced that a tentacle is now growing on you, but no one else can see
it.

|2 |A psychic wind from the Astral Plane carried psionic energy to you.
When you use your powers, faint motes of light sparkle around you.

|3 |You once suffered the dominating powers of an aboleth, leaving a
psychic splinter in your mind.

|4 |You were implanted with a mind flayer tadpole, but the ceremorphosis
never completed. And now its psionic power is yours. When you use it,
your flesh shines with a strange mucus.

|5 |As a child, you had an imaginary friend that looked like a flumph or
a strange platypus-like creature. One day, it gifted you with psionic
powers, which have ended up being not so imaginary.

|6 |Your nightmares whisper the truth to you: your psionic powers are
not your own. You draw them from your parasitic twin!
|===

==== 1st LEVEL: Psionic Spells

You learn additional spells when you reach certain levels in this class,
as shown on the Psionic Spells table. Each of these spells counts as a
sorcerer spell for you, but it doesn't count against the number of
sorcerer spells you know.

Whenever you gain a sorcerer level, you can replace one spell you gained
from this feature with another spell of the same level. The new spell
must be a divination or an enchantment spell from the sorcerer, warlock,
or wizard spell list.

Additionally, you learn how to speak and write Deep Spech.

[width="100%",cols="23%,77%",options="header",]
|===
|*Sorcerer Level* |*Spells*
|1st |arms of Hadar, dissonant whispers, mind sliver
|3rd |calm emotions, detect thoughts
|5th |hunger of Hadar, sending
|7th |Evard's black tentacles, summon aberration
|9th |Rary's telepathic bond, telekinesis
|===

==== 1st LEVEL: Telepathic Speech

You can form a telepathic connection between your mind and the mind of
another. As a bonus action, choose one creature you can see within 30
feet of you. You and the chosen creature can speak telepathically with
each other while the two of you are within a number of miles of each
other equal to your Charisma modifier (minimum of 1 mile). To understand
each other, you each must speak mentally in a language the other knows.

The telepathic connection lasts for a number of minutes equal to your
sorcerer level. It ends early if you are incapacitated or die or if you
use this ability to form a connection with a different creature.

==== 6th LEVEL: Psionic Sorcery

When you cast any spell of 1st level or higher from your Psionic Spells
feature, without spending spell points, this feature can be used only
once per spell.

Additionally, when you cast a spell this way it requires no verbal or
somatic components, and it requires no material components, unless they
are consumed by the spell.

==== 6th LEVEL: Psychic Defenses

You gain resistance to psychic damage, and you have advantage on saving
throws against being charmed or frightened.

==== 14th LEVEL: Aberrant Incarnation

At 14th level, while you are in your Sorcery Incarnate you gain the
following benefits:

* {blank}
+
____
You can see any
https://5e.tools/conditionsdiseases.html#invisible_phb[[.underline]#invisible#]
creature within 60 feet of you, provided it isn't behind total cover.
Your eyes also turn black or become writhing sensory tendrils.
____
* {blank}
+
____
You gain a flying speed equal to your walking speed, and you can hover.
As you fly, your skin glistens with mucus or shines with an otherworldly
light.
____
* {blank}
+
____
You gain a swimming speed equal to twice your walking speed, and you can
breathe underwater. Moreover, gills grow from your neck or fan out from
behind your ears, your fingers become webbed, or you grow writhing cilia
that extend through your clothing.
____
* {blank}
+
____
Your body, along with any equipment you are wearing or carrying, becomes
slimy and pliable. You can move through any space as narrow as 1 inch
without squeezing, and you can spend 5 feet of movement to escape from
nonmagical restraints or being
https://5e.tools/conditionsdiseases.html#grappled_phb[[.underline]#grappled#].
____

=== Divine Soul

Sometimes the spark of magic that fuels a sorcerer comes from a divine
source that glimmers within the soul. Having such a blessed soul is a
sign that your innate magic might come from a distant but powerful
familial connection to a divine being. Perhaps your ancestor was an
angel, transformed into a mortal and sent to fight in a god's name.

Or your birth might align with an ancient prophecy, marking you as a
servant of the gods or a chosen vessel of divine magic.

A Divine Soul, with a natural magnetism, is seen as a threat by some
religious hierarchies. As an outsider who commands sacred power, a
Divine Soul can undermine an existing order by claiming a direct tie to
the divine.

In some cultures, only those who can claim the power of a Divine Soul
may command religious power. In these lands, ecclesiastical positions
are dominated by a few bloodlines and preserved over generations.

==== 1st LEVEL: Divine Magic

Your link to the divine allows you to learn spells from the cleric
class. Choose an affinity for the source of your divine power: good,
evil or neutrality. You learn gain access to the table that your
affinity specifies. It is a sorcerer spell for you, but it doesn't count
against your number of sorcerer spells prepared. If you later replace
this spell, you must replace it with a spell from the cleric spell list.

Additionally, you learn how to speak and write Celestial.

[width="100%",cols="14%,86%",options="header",]
|===
|*Affinity* |*Spell*
|Good |Life Domain Spells
|Evil |Death Domain Spells
|Neutrality |Peace Domain Spells
|===

==== 1st LEVEL: Favored by the Gods

Starting at 1st level, divine power guards your destiny. If you fail a
saving throw or miss with an attack roll, you can roll 2d4 and add it to
the total, possibly changing the outcome. Once you use this feature, you
can't use it again until you finish a short or long rest.

==== 6th LEVEL: Empowered Healing.

Starting at 6th level, the divine energy coursing through you can
empower healing spells. When you cast a healing spell you can increase
that healing by a roll by an amount equal to a roll of d6, the number of
d6 is your Charisma modifier. You can use this trait a number of times
equals to half your proficiency bonus (rounded down), and regain all
spent uses when you finish a long rest.

==== 14th LEVEL: Divine Incarnation

At 14th level, while you are in your Sorcery Incarnate you gain the
following benefits:

* {blank}
+
____
Immunity to Charmed, Frightened and Exhaustion* condition.
____
* {blank}
+
____
Flying 60 ft.
____
* {blank}
+
____
Magic Resistance.
____

=== *Shadow Sorcerer*

You are a creature of shadow, for your innate magic comes from the
Shadowfell itself. You might trace your lineage to an entity from that
place, or perhaps you were exposed to its fell energy and transformed by
it.

The power of shadow magic casts a strange pall over your physical
presence. The spark of life that sustains you is muffled, as if it
struggles to remain viable against the dark energy that imbues your
soul. At your option, you can pick from or roll on the Shadow Sorcerer
Quirks table to create a quirk for your character.

==== Shadow Sorcerer Quirks

[width="100%",cols="7%,93%",options="header",]
|===
|d6 |Quirk
|1 |You are always icy cold to the touch.

|2 |When you are asleep, you don't appear to breathe (though you must
still breathe to survive).

|3 |You barely bleed, even when badly injured.

|4 |Your heart beats once per minute. This event sometimes surprises
you.

|5 |You have trouble remembering that living creatures and corpses
should be treated differently.

|6 |You blinked. Once. Last week.
|===

==== *1st LEVEL: Eyes of the Dark*

Starting at 1st level, you have darkvision with a range of 120 feet.

When you reach 3rd level in this class, you learn the darkness spell,
which doesn't count against your number of sorcerer spells known. You
can see through the darkness created by the spell.

==== *1st LEVEL: Shadow Magic*

You learn additional spells when you reach certain levels in this class,
as shown on the Shadow Spells table. Each of these spells counts as a
sorcerer spell for you, but it doesn't count against the number of
sorcerer spells you know.

Whenever you gain a sorcerer level, you can replace one spell you gained
from this feature with another spell of the same level. The new spell
must be an abjuration or an illusion spell from the sorcerer, warlock,
or wizard spell list.

Additionally, you learn how to speak and write Undercommon.

===== Shadow Spells Table

[width="100%",cols="22%,78%",options="header",]
|===
|*Sorcerer Level* |*Spells*
|1st |faerie fire, sleep
|3rd |moonbeam, see invisibility
|5th |gaseous form, stinking cloud
|7th |greater invisibility, stone shape
|9th |cloudkill, insect plague
|===

==== *1st LEVEL: Strength of the Grave*

Starting at 1st level, your existence in a twilight state between life
and death makes you difficult to defeat. When you are reduced to 0 hit
points but not killed outright, you can drop to 1 hit point instead. You
can't use this feature again until you finish a long rest.

==== *6thLEVEL: Hound of Ill Omen*

At 6th level, you gain the ability to call forth a howling creature of
darkness to harass your foes. You learn the *Summon Shadowspawn* spell,
and you can cast it without the material component, this summon must be
with the Fury form only.

==== *14th LEVEL: Shadow Incarnation*

At 14th level, while you are in your Sorcery Incarnate you gain the
following benefits:

* {blank}
+
____
You have resistance to necrotic and poison damage.
____
* {blank}
+
____
You are immune to poisoned and frightened conditions.
____
* {blank}
+
____
As a bonus action, you can magically teleport up to 120 feet to an
unoccupied space you can see, when you teleport you cast darkness in the
space that you want to teleport and then teleport.
____
* {blank}
+
____
You can move through other creatures and objects as if they were
difficult terrain. You take 5 force damage if you end your turn inside
an object.
____

