== *Wizard Tradition*

=== Bladesinging

Bladesingers master a tradition of wizardry that incorporates swordplay
and dance. Originally created by elves, this tradition has been adopted
by non-elf practitioners, who honor and expand on the elven ways.

In combat, a bladesinger uses a series of intricate, elegant maneuvers
that fend off harm and allow the bladesinger to channel magic into
devastating attacks and a cunning defense. Many who have observed a
bladesinger at work remember the display as one of the more beautiful
experiences in their life, a glorious dance accompanied by a singing
blade.

==== 3rd LEVEL: Training in War and Song (Bladesinging)

When you adopt this tradition at 2nd level, you gain proficiency with
light armor, and you gain proficiency with one type of one-handed melee
weapon of your choice.

You also gain proficiency in the Performance skill if you don't already
have it.

==== 3rd LEVEL: Bladesong

Starting at 2nd level, you can invoke a secret elven magic called the
Bladesong, provided you aren't wearing medium or heavy armor or using a
shield. It graces you with supernatural speed, agility, and focus.

You can use a bonus action to start the Bladesong, which lasts for 1
minute. It ends early if you are incapacitated, if you don medium or
heavy armor or a shield, or if you use two hands to make an attack with
a weapon. You can also dismiss Bladesong at any time you choose (no
action required).

While your bladesong is active, you gain the following benefits:

* {blank}
+
____
You gain a bonus to your AC equal to your Intelligence modifier (minimum
of +1).
____
* {blank}
+
____
Your walking speed increases by 10 feet.
____
* {blank}
+
____
You have advantage on Dexterity (Acrobatics) checks.
____
* {blank}
+
____
You gain a bonus to any Constitution saving throws you make to maintain
https://5e.tools/conditionsdiseases.html#concentration_phb[[.underline]#concentration#]
on a spell. The bonus equals your Intelligence modifier (minimum of +1).
____

You can use this feature a number of times equal to your proficiency
bonus, and you regain all expended uses of it when you finish a long
rest.

===== Bladesinger Styles

From its inception as a martial and magical art, Bladesinging has been
tied to the sword, more specifically the longsword. Yet many generations
of study gave rise to various styles of Bladesinging based on the melee
weapon employed. The techniques of these styles are passed from master
to students in small schools, some of which have a building dedicated to
instruction. Even the newest styles are hundreds of years old, but are
still taught by their original creators due to the long lives of elves.
Most schools of Bladesinging are in Evermeet or Evereska. One was
started in Myth Drannor, but the city's destruction has scattered those
students who survived.

Styles of Bladesinging are broadly categorized based on the type of
weapon employed, and each is associated with a category of animal.
Within that style are specializations named after specific animal types,
based on the types of spells employed, the techniques of the master, and
the particular weapon used. Bladesingers who apprentice to a master
typically get a tattoo of their chosen style's animal. Some bladesingers
learn multiple styles and bear many tattoos, wearing a warning on their
skin of their deadly skills.

*Cat.*

Styles that employ a sword belong to this family. The lion style, the
eldest, trains practitioners in the use of the longsword and doesn't
favor any particular type of spells. Leopard style focuses on the
shortsword and spells of illusion and stealth. Red tiger, a style just
three centuries old, has its bladesingers using the scimitar in a
whirling dance of defense from which they launch into sudden leaps and
attacks.

*Bird.*

Styles that focus on the use of a hafted weapon, such as an axe or
hammer, have been grouped together as bird styles, yet they vary wildly.
All relatively new styles, they use weapons not typically favored by
elves. Eagle-style bladesingers use small handaxes, and many maneuvers
in the style focus on fluid ways to throw the weapon and draw a new one.
Raven style uses a war pick, and spells associated with it grant the
bladesinger more agility in combat.

*Snake.*

Practitioners of these styles use a flail, chain, or whip. Viper style
uses a whip, despite its inelegance as a weapon, and has almost as long
a history as the lion style. Its masters punctuate their bladesong with
a stunningly rapid rhythm of whip cracks, which can keep many foes at
bay and allow the bladesinger space to cast the cruel spells of poison
and disease favored by the style.

==== 6th LEVEL: Extra Attack

Starting at 6th level, you can attack twice, instead of once, whenever
you take the Attack action on your turn. Moreover, you can cast one of
your cantrips in place of one of those attacks.

==== 10th LEVEL: Song of Defense

Beginning at 10th level, you can direct your magic to absorb damage
while your bladesong is active. When you take damage, you can use your
reaction to expend one spell slot and reduce that damage to you by an
amount equal to five times the spell's slot level.

==== 14th LEVEL: Song of Victory

Starting at 14th level, you add your Intelligence modifier (minimum of
+1) to the damage of your melee weapon attacks while your Bladesong is
active.

=== Chronurgy Magic

Focusing on the manipulation of time, those who follow the Chronurgy
tradition learn to alter the pace of reality to their liking. Using the
ramping of anticipatory dunamis energy, these mages can bend the flow of
time as adroitly as a skilled musician plays an instrument, lending
themselves and their allies an advantage in the blink of an eye.

==== 3rd LEVEL: Chronal Shift

You can magically exert limited control over the flow of time around a
creature. As a reaction, after you or a creature you can see within 30
feet of you makes an attack roll, an ability check, or a saving throw,
you can force the creature to reroll. You make this decision after you
see whether the roll succeeds or fails. The target must use the result
of the new roll.

You can use this ability a number of times equal to your Intelligence
modifier, and you regain any expended uses when you finish a long rest.

==== 3rd LEVEL: Temporal Awareness

You can add your Intelligence modifier to your initiative rolls.

==== 6th LEVEL: Momentary Stasis

As an action, you can magically force a Large or smaller creature you
can see within 60 feet of you to make a Constitution saving throw
against your spell save DC. Unless the saving throw is a success, the
creature is encased in a field of magical energy until the end of your
next turn or until the creature takes any damage. While encased in this
way, the creature is incapacitated and has a speed of 0.

You can use this feature a number of times equal to half your
proficiency bonus. You regain all expended uses when you finish a long
rest.

==== 10th LEVEL: Arcane Abeyance

When you cast a spell using a spell slot of 4th level or lower, you can
condense the spell's magic into a mote. The spell is frozen in time at
the moment of casting and held within a gray bead for 12 hours. This
bead is a Tiny object with AC 15 and 1 hit point, and it is immune to
poison and psychic damage. When the duration ends, or if the bead is
destroyed, it vanishes in a flash of light, and the spell is lost.

A creature holding the bead can use its action to release the spell
within, whereupon the bead disappears. The spell uses your spell attack
bonus and save DC, and the spell treats the creature who released it as
the caster for all other purposes.

Once you create a bead with this feature, you can't do so again until
you finish a short or long rest.

==== 14th LEVEL: Convergent Future

You can peer through possible futures and magically pull one of them
into events around you, ensuring a particular outcome. When you or a
creature you can see within 60 feet of you makes an attack roll, an
ability check, or a saving throw, you can use your reaction to ignore
the die roll and decide whether the number rolled is the minimum needed
to succeed or one less than that number (your choice).

When you use this feature, you can’t use it again until you finish a
long rest.

=== Order of Scribes

Magic of the book-that's what many folk call wizardry. The name is apt,
given how much time wizards spend poring over tomes and penning theories
about the nature of magic. It's rare to see wizards traveling without
books and scrolls sprouting from their bags, and a wizard would go to
great lengths to plumb an archive of ancient knowledge.

Among wizards, the Order of Scribes is the most bookish. It takes many
forms in different worlds, but its primary mission is the same
everywhere: recording magical discoveries so that wizardry can flourish.
And while all wizards value spellbooks, a wizard in the Order of Scribes
magically awakens their book, turning it into a trusted companion. All
wizards study books, but a wizardly scribe talks to theirs!

==== 3rd LEVEL: Wizardly Quill

As a bonus action, you can magically create a Tiny quill in your free
hand. The magic quill has the following properties:

* {blank}
+
____
The quill doesn't require ink. When you write with it, it produces ink
in a color of your choice on the writing surface.
____
* {blank}
+
____
The time you must spend to copy a spell into your spellbook equals 2
minutes per spell level if you use the quill for the transcription.
____
* {blank}
+
____
You can erase anything you write with the quill if you wave the feather
over the text as a bonus action, provided the text is within 5 feet of
you.
____

This quill disappears if you create another one or if you die.

==== 3rd LEVEL: Awakened Spellbook

Using specially prepared inks and ancient incantations passed down by
your wizardly order, you have awakened an arcane sentience within your
spellbook.

While you are holding the book, it grants you the following benefits:

* {blank}
+
____
You can use the book as a spellcasting focus for your wizard spells.
____
* {blank}
+
____
When you cast a wizard spell with a spell slot, you can temporarily
replace its damage type with a type that appears in another spell in
your spellbook, which magically alters the spell's formula for this
casting only. The latter spell must be of the same level as the spell
slot you expend.
____
* {blank}
+
____
When you cast a wizard spell as a ritual, you can use the spell's normal
casting time, rather than adding 10 minutes to it. Once you use this
benefit, you can't do so again until you finish a long rest.
____

If necessary, you can replace the book over the course of a short rest
by using your Wizardly Quill to write arcane sigils in a blank book or a
magic spellbook to which you're attuned. At the end of the rest, your
spellbook's consciousness is summoned into the new book, which the
consciousness transforms into your spellbook, along with all its spells.
If the previous book still existed somewhere, all the spells vanish from
its pages.

==== 6th LEVEL: Manifest Mind

You can conjure forth the mind of your Awakened Spellbook. As a bonus
action while the book is on your person, you can cause the mind to
manifest as a Tiny spectral object, hovering in an unoccupied space of
your choice within 60 feet of you. The spectral mind is intangible and
doesn't occupy its space, and it sheds dim light in a 10-foot radius. It
looks like a ghostly tome, a cascade of text, or a scholar from the past
(your choice).

While manifested, the spectral mind can hear and see, and it has
darkvision with a range of 60 feet. The mind can telepathically share
with you what it sees and hears (no action required).

Whenever you cast a wizard spell on your turn, you can cast it as if you
were in the spectral mind's space, instead of your own, using its
senses. You can do so a number of times per day equal to your
proficiency bonus, and you regain all expended uses when you finish a
long rest.

As a bonus action, you can cause the spectral mind to hover up to 30
feet to an unoccupied space that you or it can see. It can pass through
creatures but not objects.

The spectral mind stops manifesting if it is ever more than 300 feet
away from you, if someone casts dispel magic on it, if the Awakened
Spellbook is destroyed, if you die, or if you dismiss the spectral mind
as a bonus action.

Once you conjure the mind, you can't do so again until you finish a long
rest, unless you expend a spell slot of any level to conjure it again.

==== 10th LEVEL: Master Scrivener

Whenever you finish a long rest, you can create one magic scroll by
touching your Wizardly Quill to a blank piece of paper or parchment and
causing one spell from your Awakened Spellbook to be copied onto the
scroll. The spellbook must be within 5 feet of you when you make the
scroll.

The chosen spell must be of 1st or 2nd level and must have a casting
time of 1 action. Once in the scroll, the spell's power is enhanced,
counting as one level higher than normal. You can cast the spell from
the scroll by reading it as an action. The scroll is unintelligible to
anyone else, and the spell vanishes from the scroll when you cast it or
when you finish your next long rest.

You are also adept at crafting spell scrolls, which are described in the
treasure chapter of the Dungeon Master's Guide. The gold and time you
must spend to make such a scroll are halved if you use your Wizardly
Quill.

==== 14th LEVEL: One with the Word

Your connection to your Awakened Spellbook has become so profound that
your soul has become entwined with it. While the book is on your person,
you have advantage on all Intelligence (Arcana) checks, as the spellbook
helps you remember magical lore.

Moreover, if you take damage while your spellbook's mind is manifested,
you can prevent all of that damage to you by using your reaction to
dismiss the spectral mind, using its magic to save yourself. Then roll
3d6. The spellbook temporarily loses spells of your choice that have a
combined spell level equal to that roll or higher. For example, if the
roll's total is 9, spells vanish from the book that have a combined
level of at least 9, which could mean one 9th-level spell, three
3rd-level spells, or some other combination. If there aren't enough
spells in the book to cover this cost, you drop to 0 hit points.

Until you finish 1d6 long rests, you are incapable of casting the lost
spells, even if you find them on a scroll or in another spellbook. After
you finish the required number of rests, the spells reappear in the
spellbook.

Once you use this reaction, you can't do so again until you finish a
long rest.
