== *Wizard*

[width="100%",cols="13%,6%,37%,8%,4%,4%,4%,4%,4%,4%,4%,4%,4%",options="header",]
|===
| | | | |*_Spell Slots per Spell Level_* | | | | | | | |
|*_Level_* a|
*_Prof._*

*_Bonus_*

|*_Features_* |*_Cantrips Known_* |*_1st_* |*_2nd_* |*_3rd_* |*_4th_*
|*_5th_* |*_6th_* |*_7th_* |*_8th_* |*_9th_*

|*1st* |*+2* |*Spellcasting* |*3* |*2* |*—* |*—* |*—* |*—* |*—* |*—*
|*—* |*—*

|*2nd* |*+2* |*Arcane Recovery, Cantrip Formulas* |*3* |*3* |*—* |*—*
|*—* |*—* |*—* |*—* |*—* |*—*

|*3rd* |*+2* |*Arcane Tradition* |*3* |*4* |*2* |*—* |*—* |*—* |*—* |*—*
|*—* |*—*

|*4th* |*+2* |*Ability Score Improvement* |*4* |*4* |*3* |*—* |*—* |*—*
|*—* |*—* |*—* |*—*

|*5th* |*+3* |*School Savant* |*4* |*4* |*3* |*2* |*—* |*—* |*—* |*—*
|*—* |*—*

|*6th* |*+3* |*Arcane Tradition feature* |*4* |*4* |*3* |*3* |*—* |*—*
|*—* |*—* |*—* |*—*

|*7th* |*+3* |*—* |*4* |*4* |*3* |*3* |*1* |*—* |*—* |*—* |*—* |*—*

|*8th* |*+3* |*Ability Score Improvement* |*4* |*4* |*3* |*3* |*2* |*—*
|*—* |*—* |*—* |*—*

|*9th* |*+4* |*—* |*4* |*4* |*3* |*3* |*3* |*1* |*—* |*—* |*—* |*—*

|*10th* |*+4* |*Arcane Tradition feature* |*5* |*4* |*3* |*3* |*3* |*2*
|*—* |*—* |*—* |*—*

|*11th* |*+4* |*School Mastery* |*5* |*4* |*3* |*3* |*3* |*2* |*1* |*—*
|*—* |*—*

|*12th* |*+4* |*Ability Score Improvement* |*5* |*4* |*3* |*3* |*3* |*2*
|*1* |*—* |*—* |*—*

|*13th* |*+5* |*—* |*5* |*4* |*3* |*3* |*3* |*2* |*1* |*1* |*—* |*—*

|*14th* |*+5* |*Arcane Tradition feature* |*5* |*4* |*3* |*3* |*3* |*2*
|*1* |*1* |*—* |*—*

|*15th* |*+5* |*—* |*5* |*4* |*3* |*3* |*3* |*2* |*1* |*1* |*1* |*—*

|*16th* |*+5* |*Ability Score Improvement* |*5* |*4* |*3* |*3* |*3* |*2*
|*1* |*1* |*1* |*—*

|*17th* |*+6* |*—* |*5* |*4* |*3* |*3* |*3* |*2* |*1* |*1* |*1* |*1*

|*18th* |*+6* |*Spell Mastery* |*5* |*4* |*3* |*3* |*3* |*3* |*1* |*1*
|*1* |*1*

|*19th* |*+6* |*Ability Score Improvement* |*5* |*4* |*3* |*3* |*3* |*3*
|*2* |*1* |*1* |*1*

|*20th* |*+6* |*Create Spell* |*5* |*4* |*3* |*3* |*3* |*3* |*2* |*2*
|*1* |*1*
|===

[width="99%"]
|===
|
*Hit Points*

*_Hit Dice_*: 1d6

*_Hit Points at 1st Level_*: 6 + your Constitution modifier

*_Hit Points at Higher Levels_*: 1d6 (or 4) + your Constitution modifier
per Wizard level after 1st
|
*Proficiencies*

*_Armor_*: none

*_Weapons_*: daggers, darts, slings, quarterstaffs, light crossbows

*_Tools:_* none

*_Saving Throws_*: Intelligence, Wisdom

*_Skills_*: Choose 2 from Arcana, History, Insight, Investigation,
Medicine, and Religion.
a|
*Starting Equipment*

You start with the following items, plus anything provided by your
background.

* {blank}
+
____
{empty}(a) a quarterstaff or (b) a dagger
____
* {blank}
+
____
{empty}(a) a component pouch or (b) an arcane focus
____
* {blank}
+
____
{empty}(a) a scholar's pack or (b) an explorer's pack
____
* {blank}
+
____
A spellbook
____
|===

=== *Spellcasting*

==== *Cantrips*

At 1st level, you know three cantrips of your choice from the wizard
spell list. You learn additional wizard cantrips of your choice at
higher levels, as shown in the Cantrips Known column of the Wizard
table. Additionally, you learn the Prestidigitation cantrip, that
doesn’t count to your Cantrips Known.

==== *Spellbook*

At 1st level, you have a spellbook containing six 1st-level wizard
spells of your choice. Your spellbook is the repository of the wizard
spells you know, except your cantrips, which are fixed in your mind.

In case that you lose your spellbook you retain all your spells until
you use one spell, you will have to succeed a Intelligence check DC 10
or lose it. You can put your known spell into a new spellbook by a
quarter the cost and time.

==== *Preparing and Casting Spells*

The Wizard table shows how many spell slots you have to cast your wizard
spells of 1st level and higher. To cast one of these spells, you must
expend a slot of the spell's level or higher. You regain all expended
spell slots when you finish a long rest.

You have prepared all the spells that are in your book. Casting a spell
doesn't remove it from your list of prepared spells.

==== *Spellcasting Ability*

Intelligence is your spellcasting ability for your wizard spells, since
you learn your wizard spells through dedicated study and memorization.
You use your Intelligence whenever a spell refers to your spellcasting
ability. In addition, you use your Intelligence modifier when setting
the saving throw DC for a wizard spell you cast and when making an
attack roll with one.

____
*Spell save DC* = 8 + your proficiency bonus + your Intelligence
modifier +
*Spell attack modifier* = your proficiency bonus + your Intelligence
modifier
____

==== *Ritual Casting*

You can cast a wizard spell as a ritual if that spell has the ritual tag
and you have the spell in your spellbook.

==== *Spellcasting Focus*

You can use an arcane focus as a spellcasting focus for your wizard
spells.

==== *Learning Spells of 1st Level and Higher*

Each time you gain a wizard level, you can add two wizard spells of your
choice to your spellbook. Each of these spells must be of a level for
which you have spell slots, as shown on the Wizard table. On your
adventures, you might find other spells that you can add to your
spellbook (see "Your Spellbook").

==== *Your Spellbook*

The spells that you add to your spellbook as you gain levels reflect the
arcane research you conduct on your own, as well as intellectual
breakthroughs you have had about the nature of the multiverse. You might
find other spells during your adventures. You could discover a spell
recorded on a scroll in an evil wizard's chest, for example, or in a
dusty tome in an ancient library.

A spellbook doesn't contain cantrips.

===== *Copying a Spell into the Book.*

When you find a wizard spell of 1st level or higher, you can add it to
your spellbook if it is of a spell level you can prepare and if you can
spare the time to decipher and copy it.

Copying a spell into your spellbook involves reproducing the basic form
of the spell, then deciphering the unique system of notation used by the
wizard who wrote it. You must practice the spell until you understand
the sounds or gestures required, then transcribe it into your spellbook
using your own notation.

For each level of the spell, the process takes 2 hours and costs 50 gp.
The cost represents material components you expend as you experiment
with the spell to master it, as well as the fine inks you need to record
it. Once you have spent this time and money, you can prepare the spell
just like your other spells.

===== *Copying from a Spell Scroll.*

A wizard spell on a spell scroll can be copied just as spells in
spellbooks can be copied. When you copy a spell from a spell scroll, you
must succeed on an Intelligence (Arcana) check with a DC equal to 10 +
the spell's level. If the check succeeds, the spell is successfully
copied. Whether the check succeeds or fails, the spell scroll is
destroyed.

===== *Replacing the Book.*

You can copy a spell from your own spellbook into another book—for
example, if you want to make a backup copy of your spellbook. This is
just like copying a new spell into your spellbook, but faster and
easier, since you understand your own notation and already know how to
cast the spell. You need to spend only 1 hour and 10 gp for each level
of the copied spell.

If you lose your spellbook, you can use the same procedure to transcribe
the spells that you have prepared into a new spellbook. Filling out the
remainder of your spellbook requires you to find new spells to do so, as
normal. For this reason, many wizards keep backup spellbooks in a safe
place.

===== *The Book's Appearance.*

Your spellbook is a unique compilation of spells, with its own
decorative flourishes and margin notes. It might be a plain, functional
leather volume that you received as a gift from your master, a finely
bound gilt-edged tome you found in an ancient library, or even a loose
collection of notes scrounged together after you lost your previous
spellbook in a mishap.

=== Arcane Recovery

At 2nd level, you have learned to regain some of your magical energy by
studying your spellbook. Once per day when you finish a short rest, you
can choose expended spell slots to recover. The spell slots can have a
combined level that is equal to or less than half your wizard level
(rounded up), and none of the slots can be 6th level or higher.

For example, if you're a 4th-level wizard, you can recover up to two
levels worth of spell slots.

You can recover either a 2nd-level spell slot or two 1st-level spell
slots.

=== Cantrip Formula

At 2nd level, you have scribed a set of arcane formulas in your
spellbook that you can use to formulate a cantrip in your mind. Whenever
you finish a long rest and consult those formulas in your spellbook, you
can replace one wizard cantrip you know with another cantrip from the
wizard spell list.

=== *Arcane Tradition*

When you reach 3nd level, you choose an arcane tradition from the list
of available traditions, shaping your practice of magic. Your choice
grants you features at 2nd level and again at 6th, 10th, and 14th level.

=== *Ability Score Improvement*

When you reach 4th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== School Savant

At 5th level, you choose a school of magic, and you gain the following
traits:

* {blank}
+
____
The gold and time you must spend to copy a spell from your chosen school
into your spellbook is halved.
____
* {blank}
+
____
You can cast a spell from that school without spending a spell slot,
once you use this feature you can’t use it until you finish a long rest.
____

Additionally, you can’t lose the spells that are from your School of
magic.

=== *Arcane Tradition feature*

At 6th level, you gain a feature granted by your Arcane Tradition.

=== *Ability Score Improvement*

When you reach 8th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Arcane Tradition feature*

At 10th level, you gain a feature granted by your Arcane Tradition.

=== School Mastery

At 11th level, you gain mastery in the school you choose from your
School Savant:

==== *Abjuration*

*Arcane Ward*. you can weave magic around yourself for protection. When
you cast an abjuration spell of 1st level or higher, you can
simultaneously use a strand of the spell's magic to create a magical
ward on yourself that lasts until you finish a long rest. The ward has a
hit point maximum equal to twice your wizard level + your Intelligence
modifier. Whenever you or a creature that you can see at 30 feets of
you, take damage, the ward takes the damage instead. If this damage
reduces the ward to 0 hit points, you take any remaining damage. The
ward use the resistance of the target creature.

While the ward has 0 hit points, it can't absorb damage, but its magic
remains. Whenever you cast an abjuration spell of 1st level or higher,
the ward regains a number of hit points equal to your Intelligence
modifier + twice the level of the spell.

==== *Conjuration.*

*Conjured.* you can use your action to conjure up an inanimate object in
your hand or on the ground in an unoccupied space that you can see
within 10 feet of you. This object can be no larger than 3 feet on a
side and weigh no more than 10 pounds, and its form must be that of a
non magical object that you have seen. The object is visibly magical,
radiating dim light out to 5 feet.

The object remains a number of hours equal to your Wizard level, when
you use this feature again, if it takes any damage, or if it deals any
damage.

Additionally, your conjuration spell that summons a creature doesn’t
require concentration for you, but you can’t have more than 1 creature
summoned this way.

==== *Divination*.

*Portent.* glimpses of the future begin to press in on your awareness.
When you finish a long rest, roll two d20s and record the numbers
rolled. You can replace any attack roll, saving throw, or ability check
made by you or a creature that you can see at 30 feets of you, with one
of these foretelling rolls. You must choose to do so before the roll,
and you can replace a roll in this way only once per turn.

Each foretelling roll can be used only once. When you finish a long
rest, you lose any unused foretelling rolls.

==== *Enchantment*.

*Split Enchantment.* When you cast an enchantment spell of 1st level or
higher that targets only one creature, you can have it target a number
of creatures equal to your Intelligence modifier.

Additionally, when you cast an enchantment spell to charm one or more
creatures, you can alter one creature's understanding so that it remains
unaware of being charmed.

==== *Evocation*.

*Overchannel*.When you cast a wizard spell of 1st through 5th-level that
deals damage, you can deal maximum damage with that spell. Once you cast
a spell this way, you can’t do it again until you finish a long rest.

==== *Illusion*.

*Illusory Self*. you can create an illusory duplicate of yourself as an
instant, almost instinctual reaction to danger. When a creature makes an
attack roll against you, you can use your reaction to interpose the
illusory duplicate between the attacker and yourself. The attack
automatically misses you, then the illusion dissipates.

You can use this trait twice and regain any spent use when you finish a
long rest.

Additionally, when you cast an illusion spell that has a duration of 1
minute or longer, you can use your action to change the nature of that
illusion (using the spell's normal parameters for the illusion),
provided that you can see the illusion.

==== *Necromancy*.

*Undead Thralls*. you add the animated dead spell to your spellbook if
it is not there already. When you cast animate dead, you can target one
additional corpse or pile of bones, creating another zombie or skeleton,
as appropriate.

Whenever you create an undead using a necromancy spell, it has
additional benefits:

* {blank}
+
____
The creature's hit point maximum is increased by an amount equal to your
wizard level.
____
* {blank}
+
____
The creature adds your proficiency bonus to its weapon damage rolls.
____

Additionally, you can use magic to bring undead under your control, even
those created by other wizards. As an action, you can choose one undead
that you can see within 60 feet of you. That creature must make a
Charisma saving throw against your wizard spell save DC. If it succeeds,
you can't use this feature on it again. If it fails, it becomes friendly
to you and obeys your commands until you use this feature again.

Intelligent undead are harder to control in this way. If the target has
an Intelligence of 8 or higher, it has advantage on the saving throw. If
it fails the saving throw and has an Intelligence of 12 or higher, it
can repeat the saving throw at the end of every hour until it succeeds
and breaks free.

==== *Transtumation*.

*Transmuter's Stone*. You can spend 8 hours creating a transmuter's
stone that stores transmutation magic. You can benefit from the stone
yourself or give it to another creature. A creature gains a benefit of
your choice as long as the stone is in the creature's possession. When
you create the stone, choose the benefit from the following options:

* {blank}
+
____
Darkvision out to a range of 60 feet, as described in chapter 8.
____
* {blank}
+
____
An increase to speed of 10 feet while the creature is unencumbered.
____
* {blank}
+
____
Proficiency in Constitution saving throws.
____
* {blank}
+
____
Resistance to acid, cold, fire, lightning, or thunder damage (your
choice whenever you choose this benefit).
____

Each time you cast a transmutation spell of 1st level or higher, you can
change the effect of your stone if the stone is on your person.

If you create a new transmuter's stone, the previous one ceases to
function

=== *Ability Score Improvement*

When you reach 12th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Arcane Tradition feature*

At 14th level, you gain a feature granted by your Arcane Tradition.

=== *Ability Score Improvement*

When you reach 16th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== *Spell Mastery*

At 18th level, you have achieved such mastery over certain spells that
you can cast them at will. Choose a 1st-level wizard spell and a
2nd-level wizard spell that are in your spellbook. You can cast those
spells at their lowest level without expending a spell slot when you
have them prepared. If you want to cast either spell at a higher level,
you must expend a spell slot as normal.

By spending 8 hours in study, you can exchange one or both of the spells
you chose for different spells of the same levels.

=== *Ability Score Improvement*

When you reach 19th level, you can increase one ability score of your
choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can't increase an ability score above 20 using this
feature.

If your DM allows the use of feats, you may instead take a feat.

=== Create Spell

When you reach 20th level, you are able to create new spells, for that
you must choose a spell that you know from your spellbook and perform a
ritual that takes 1 hour to perform for each level of the spell. You
need to use an Arcane Focus worth at least 1,000 gp for each level of
the spell. Additionally you need to spend a 4th level spell slot for
each component that you want to modify above the 4th level. Then you can
choose which component to modify from the following list:

* {blank}
+
____
*Components*. Remove one of the spell’s components: Verbal, Somatic, or
Material. You can’t remove the Material component of a spell that
consumes that component.
____
* {blank}
+
____
*Concentration*. If the spell requires Concentration, damage can’t break
your Concentration on the spell.
____
* {blank}
+
____
*Damage Type*. If the spell has a damage type, replace it with one of
the following types: Acid, Cold, Fire, Lightning, Necrotic, Poison, or
Thunder. If the spell has multiple damage types, you can change only one
of them.
____
* {blank}
+
____
*Range*. If the spell has a range of at least 5 feet and doesn’t have a
range of Self, increase its range by a number of feet equal to 30 times
your Wizard level.
____
* {blank}
+
____
*Ritual*. If the spell lacks the Ritual tag and has a casting time of at
least 10 minutes, give it the Ritual tag.
____
* {blank}
+
____
*Targets*. If the spell affects one or more creatures and doesn’t have a
range of Self, it now affects only your allies or enemies (choose which
when you modify the spell).
____

When you finish the spell appears in your spellbook, you have it
prepared and doesn’t count for your spell prepared. This spell has the
name of your choice.

include::wizard_subclass.adoc[]
