== Aasimar

*Creature Type:* Humanoid (Aasimar)

*Size:* Medium

*Speed:* 30 ft.

*Age:* Mature at 20 and usualy live up to 110

'''

*Darkvision.* You can see in dim light within 60 feet of you as if it were bright light and in darkness as if it were dim light. You discern colors in that darkness only as shades of gray.

*Celestial Lineague.* At 3rd the god’s alignment that bless your lineage give you one of the following traits:

* Good Alignment.
** You gain resistance to radiant damage.
** Angelical Protection. As a bonus action you talk to a one creature that can hear you that is up to 15 ft from you (including yourself) the target gains 1d6 temporary hit points, the roll increases to 2d6 at 5th level and 3d6 at 11th level. You can use this trait a number of times equals to half your proficiency bonus.
* Evil Alignment.
** You gain resistance to necrotic damage.
** Necrotic Shroud. As a bonus action you can force creatures other than your allies within 10 ft of you that can see you must succeed on a Charisma saving throw (DC 8 + your proficiency bonus + your Charisma modifier) or become frightened of you for a number or rounds equal to your proficiency bonus. You can use this trait a number of times equals to half your proficiency bonus.
* Chaotic Alignment.
** You gain resistance to force damage.
** Chaotic Energy. As a bonus action you can imbue one attack of your next spell attack to deal extra 1d6 force damage, the damage increase to 2d6 at 7th level and 3d6 at 11th level. You can use this trait a number of times equals to half your proficiency bonus.
* Lawful Alignment.
** You gain resistance to psychic damage.
** Divine Mind. As a bonus action you can give yourself the following benefits during the next minute:
* Advantage on Intelligence and Wisdom Saving throws.
** You can add your proficiency bonus to all Intelligence checks (skills included).
** You can use this trait a number of times equals to your proficiency bonus.

*Languague.* You can speak, read, and write Common.

'''

*Height.* 4'8" + 2d10.

*Weight.* 110 + (2d10 * 2d4) lb.

